// ── Built-in food database ───────────────────────────────────────────────────
//
// Curated nutrition reference the athlete can log from without typing macros.
// Values are per the stated serving (USDA / IFCT averages, rounded). The list
// deliberately mixes whole foods with common cooked dishes (incl. Indian
// staples) so day-to-day logging rarely needs manual entry.

export type FoodCategory =
  | 'custom'
  | 'fruits'
  | 'vegetables'
  | 'grains'
  | 'protein'
  | 'dairy'
  | 'meals'
  | 'snacks'
  | 'drinks'
  | 'fastfood';

export interface FoodItem {
  name: string;
  category: FoodCategory;
  /** kcal per serving. */
  calories: number;
  /** Human serving descriptor the calories refer to. */
  serving: string;
  /** Macros in grams per serving. */
  protein: number;
  carbs: number;
  fat: number;
}

export const FOOD_CATEGORY_LABELS: Record<FoodCategory, string> = {
  custom: 'My Foods',
  fruits: 'Fruits',
  vegetables: 'Vegetables',
  grains: 'Grains & Breads',
  protein: 'Protein',
  dairy: 'Dairy',
  meals: 'Meals & Dishes',
  snacks: 'Snacks & Sweets',
  drinks: 'Drinks',
  fastfood: 'Fast Food',
};

export const FOOD_LIBRARY: FoodItem[] = [
  // ── Fruits ──────────────────────────────────────────────────────────────
  { name: 'Apple', category: 'fruits', calories: 95, serving: '1 medium', protein: 0.5, carbs: 25, fat: 0.3 },
  { name: 'Banana', category: 'fruits', calories: 105, serving: '1 medium', protein: 1.3, carbs: 27, fat: 0.4 },
  { name: 'Orange', category: 'fruits', calories: 62, serving: '1 medium', protein: 1.2, carbs: 15, fat: 0.2 },
  { name: 'Mango', category: 'fruits', calories: 200, serving: '1 whole', protein: 2.8, carbs: 50, fat: 1.3 },
  { name: 'Grapes', category: 'fruits', calories: 104, serving: '1 cup', protein: 1.1, carbs: 27, fat: 0.2 },
  { name: 'Watermelon', category: 'fruits', calories: 46, serving: '1 cup cubes', protein: 0.9, carbs: 12, fat: 0.2 },
  { name: 'Papaya', category: 'fruits', calories: 62, serving: '1 cup cubes', protein: 0.7, carbs: 16, fat: 0.4 },
  { name: 'Pomegranate', category: 'fruits', calories: 144, serving: '1 cup arils', protein: 2.9, carbs: 33, fat: 2 },
  { name: 'Strawberries', category: 'fruits', calories: 49, serving: '1 cup', protein: 1, carbs: 12, fat: 0.5 },
  { name: 'Blueberries', category: 'fruits', calories: 84, serving: '1 cup', protein: 1.1, carbs: 21, fat: 0.5 },
  { name: 'Pineapple', category: 'fruits', calories: 82, serving: '1 cup chunks', protein: 0.9, carbs: 22, fat: 0.2 },
  { name: 'Kiwi', category: 'fruits', calories: 42, serving: '1 fruit', protein: 0.8, carbs: 10, fat: 0.4 },
  { name: 'Pear', category: 'fruits', calories: 101, serving: '1 medium', protein: 0.6, carbs: 27, fat: 0.2 },
  { name: 'Guava', category: 'fruits', calories: 37, serving: '1 fruit', protein: 1.4, carbs: 8, fat: 0.5 },
  { name: 'Chikoo (Sapota)', category: 'fruits', calories: 80, serving: '1 fruit', protein: 0.4, carbs: 20, fat: 1.1 },
  { name: 'Dates', category: 'fruits', calories: 66, serving: '1 date (Medjool)', protein: 0.4, carbs: 18, fat: 0 },
  { name: 'Avocado', category: 'fruits', calories: 240, serving: '1 whole', protein: 3, carbs: 13, fat: 22 },
  { name: 'Coconut (fresh)', category: 'fruits', calories: 99, serving: '1 piece (28 g)', protein: 0.9, carbs: 4.3, fat: 9.4 },
  { name: 'Apricot', category: 'fruits', calories: 17, serving: '1 fruit', protein: 0.5, carbs: 3.9, fat: 0.1 },
  { name: 'Peach', category: 'fruits', calories: 59, serving: '1 medium', protein: 1.4, carbs: 14, fat: 0.4 },
  { name: 'Plum', category: 'fruits', calories: 30, serving: '1 fruit', protein: 0.5, carbs: 8, fat: 0.2 },
  { name: 'Cherries', category: 'fruits', calories: 87, serving: '1 cup', protein: 1.5, carbs: 22, fat: 0.3 },
  { name: 'Raspberries', category: 'fruits', calories: 64, serving: '1 cup', protein: 1.5, carbs: 15, fat: 0.8 },
  { name: 'Blackberries', category: 'fruits', calories: 62, serving: '1 cup', protein: 2, carbs: 14, fat: 0.7 },
  { name: 'Lychee', category: 'fruits', calories: 66, serving: '10 fruits', protein: 0.8, carbs: 16, fat: 0.4 },
  { name: 'Jackfruit', category: 'fruits', calories: 157, serving: '1 cup', protein: 2.8, carbs: 38, fat: 1 },
  { name: 'Custard Apple (Sitaphal)', category: 'fruits', calories: 94, serving: '1 fruit', protein: 2, carbs: 22, fat: 0.6 },
  { name: 'Jamun (Java Plum)', category: 'fruits', calories: 60, serving: '1 cup', protein: 0.7, carbs: 15, fat: 0.2 },
  { name: 'Muskmelon', category: 'fruits', calories: 53, serving: '1 cup cubes', protein: 1.3, carbs: 13, fat: 0.3 },
  { name: 'Honeydew Melon', category: 'fruits', calories: 61, serving: '1 cup cubes', protein: 0.8, carbs: 15, fat: 0.2 },
  { name: 'Dragon Fruit', category: 'fruits', calories: 60, serving: '1 fruit', protein: 1.2, carbs: 13, fat: 0.4 },
  { name: 'Fig (fresh)', category: 'fruits', calories: 37, serving: '1 fruit', protein: 0.4, carbs: 10, fat: 0.2 },
  { name: 'Dried Figs (Anjeer)', category: 'fruits', calories: 93, serving: '3 figs', protein: 1, carbs: 24, fat: 0.3 },
  { name: 'Raisins', category: 'fruits', calories: 85, serving: '¼ cup', protein: 0.9, carbs: 22, fat: 0.1 },
  { name: 'Dried Apricots', category: 'fruits', calories: 78, serving: '5 pieces', protein: 1.1, carbs: 20, fat: 0.2 },
  { name: 'Prunes', category: 'fruits', calories: 91, serving: '4 prunes', protein: 0.8, carbs: 24, fat: 0.1 },
  { name: 'Cranberries (dried)', category: 'fruits', calories: 92, serving: '¼ cup', protein: 0.1, carbs: 25, fat: 0.4 },
  { name: 'Amla (Indian Gooseberry)', category: 'fruits', calories: 27, serving: '2 fruits', protein: 0.5, carbs: 6, fat: 0.3 },
  { name: 'Starfruit', category: 'fruits', calories: 28, serving: '1 fruit', protein: 1, carbs: 6, fat: 0.3 },
  { name: 'Passion Fruit', category: 'fruits', calories: 17, serving: '1 fruit', protein: 0.4, carbs: 4, fat: 0.1 },
  { name: 'Grapefruit', category: 'fruits', calories: 52, serving: '½ fruit', protein: 1, carbs: 13, fat: 0.2 },
  { name: 'Sweet Lime (Mosambi)', category: 'fruits', calories: 43, serving: '1 fruit', protein: 0.8, carbs: 9.5, fat: 0.3 },
  { name: 'Pomelo', category: 'fruits', calories: 72, serving: '1 cup', protein: 1.4, carbs: 18, fat: 0.1 },
  { name: 'Mulberries', category: 'fruits', calories: 60, serving: '1 cup', protein: 2, carbs: 14, fat: 0.6 },
  { name: 'Ber (Indian Jujube)', category: 'fruits', calories: 35, serving: '5 fruits', protein: 0.6, carbs: 8, fat: 0.1 },
  { name: 'Tamarind Pulp', category: 'fruits', calories: 72, serving: '2 tbsp (30 g)', protein: 0.8, carbs: 19, fat: 0.2 },
  { name: 'Green Mango (raw)', category: 'fruits', calories: 60, serving: '1 cup sliced', protein: 0.8, carbs: 15, fat: 0.3 },
  { name: 'Persimmon', category: 'fruits', calories: 118, serving: '1 fruit', protein: 1, carbs: 31, fat: 0.3 },
  { name: 'Rambutan', category: 'fruits', calories: 60, serving: '8 fruits', protein: 0.7, carbs: 15, fat: 0.2 },
  { name: 'Clementine', category: 'fruits', calories: 35, serving: '1 fruit', protein: 0.6, carbs: 9, fat: 0.1 },
  { name: 'Green Apple', category: 'fruits', calories: 80, serving: '1 medium', protein: 0.4, carbs: 21, fat: 0.2 },
  { name: 'Lemon', category: 'fruits', calories: 22, serving: '1 fruit', protein: 0.4, carbs: 4.7, fat: 0.1 },
  { name: 'Tender Coconut Malai', category: 'fruits', calories: 80, serving: '½ cup', protein: 1, carbs: 4, fat: 7 },
  { name: 'Fruit Salad (mixed)', category: 'fruits', calories: 90, serving: '1 cup', protein: 1.2, carbs: 22, fat: 0.4 },
  { name: 'Fruit Chaat', category: 'fruits', calories: 120, serving: '1 katori', protein: 2, carbs: 28, fat: 0.5 },

  // ── Vegetables ──────────────────────────────────────────────────────────
  { name: 'Broccoli (steamed)', category: 'vegetables', calories: 55, serving: '1 cup', protein: 3.7, carbs: 11, fat: 0.6 },
  { name: 'Spinach (cooked)', category: 'vegetables', calories: 41, serving: '1 cup', protein: 5.3, carbs: 6.8, fat: 0.5 },
  { name: 'Carrot', category: 'vegetables', calories: 25, serving: '1 medium', protein: 0.6, carbs: 6, fat: 0.1 },
  { name: 'Cucumber', category: 'vegetables', calories: 16, serving: '1 cup sliced', protein: 0.7, carbs: 4, fat: 0.1 },
  { name: 'Tomato', category: 'vegetables', calories: 22, serving: '1 medium', protein: 1.1, carbs: 4.8, fat: 0.2 },
  { name: 'Sweet Potato (baked)', category: 'vegetables', calories: 103, serving: '1 medium', protein: 2.3, carbs: 24, fat: 0.2 },
  { name: 'Potato (boiled)', category: 'vegetables', calories: 87, serving: '1 medium', protein: 1.9, carbs: 20, fat: 0.1 },
  { name: 'Cauliflower (cooked)', category: 'vegetables', calories: 29, serving: '1 cup', protein: 2.3, carbs: 5, fat: 0.6 },
  { name: 'Green Peas', category: 'vegetables', calories: 134, serving: '1 cup', protein: 8.6, carbs: 25, fat: 0.4 },
  { name: 'Bell Pepper', category: 'vegetables', calories: 31, serving: '1 medium', protein: 1, carbs: 7, fat: 0.3 },
  { name: 'Onion', category: 'vegetables', calories: 44, serving: '1 medium', protein: 1.2, carbs: 10, fat: 0.1 },
  { name: 'Beetroot (cooked)', category: 'vegetables', calories: 75, serving: '1 cup', protein: 2.9, carbs: 17, fat: 0.3 },
  { name: 'Mushrooms (sautéed)', category: 'vegetables', calories: 44, serving: '1 cup', protein: 3.4, carbs: 6.4, fat: 0.7 },
  { name: 'Mixed Salad (no dressing)', category: 'vegetables', calories: 33, serving: '2 cups', protein: 2, carbs: 6.5, fat: 0.4 },
  { name: 'Corn (boiled)', category: 'vegetables', calories: 96, serving: '1 ear', protein: 3.4, carbs: 21, fat: 1.5 },
  { name: 'Bhindi Sabzi (okra)', category: 'vegetables', calories: 150, serving: '1 katori', protein: 3, carbs: 12, fat: 10 },
  { name: 'Aloo Gobi', category: 'vegetables', calories: 180, serving: '1 katori', protein: 4, carbs: 22, fat: 9 },
  { name: 'Baingan Bharta', category: 'vegetables', calories: 165, serving: '1 katori', protein: 3.5, carbs: 14, fat: 11 },
  { name: 'Cabbage (cooked)', category: 'vegetables', calories: 35, serving: '1 cup', protein: 1.9, carbs: 8, fat: 0.1 },
  { name: 'Zucchini (sautéed)', category: 'vegetables', calories: 29, serving: '1 cup', protein: 1.2, carbs: 5, fat: 0.9 },
  { name: 'Pumpkin (cooked)', category: 'vegetables', calories: 49, serving: '1 cup', protein: 1.8, carbs: 12, fat: 0.2 },
  { name: 'Lettuce', category: 'vegetables', calories: 8, serving: '2 cups', protein: 0.6, carbs: 1.6, fat: 0.1 },
  { name: 'Kale (cooked)', category: 'vegetables', calories: 36, serving: '1 cup', protein: 2.5, carbs: 7, fat: 0.5 },
  { name: 'Asparagus (grilled)', category: 'vegetables', calories: 27, serving: '8 spears', protein: 2.9, carbs: 5, fat: 0.2 },
  { name: 'Brussels Sprouts (roasted)', category: 'vegetables', calories: 80, serving: '1 cup', protein: 4, carbs: 11, fat: 3.5 },
  { name: 'Green Beans (steamed)', category: 'vegetables', calories: 44, serving: '1 cup', protein: 2.4, carbs: 10, fat: 0.4 },
  { name: 'Radish', category: 'vegetables', calories: 19, serving: '1 cup sliced', protein: 0.8, carbs: 4, fat: 0.1 },
  { name: 'Turnip (cooked)', category: 'vegetables', calories: 34, serving: '1 cup', protein: 1.1, carbs: 8, fat: 0.1 },
  { name: 'Celery', category: 'vegetables', calories: 11, serving: '2 stalks', protein: 0.5, carbs: 2.4, fat: 0.1 },
  { name: 'Spring Onion', category: 'vegetables', calories: 19, serving: '½ cup chopped', protein: 0.9, carbs: 3.7, fat: 0.1 },
  { name: 'Olives', category: 'vegetables', calories: 59, serving: '10 olives', protein: 0.4, carbs: 3, fat: 6 },
  { name: 'Artichoke (cooked)', category: 'vegetables', calories: 64, serving: '1 medium', protein: 3.5, carbs: 14, fat: 0.4 },
  { name: 'Drumstick (Moringa) Pods', category: 'vegetables', calories: 37, serving: '1 cup pieces', protein: 2, carbs: 8, fat: 0.2 },
  { name: 'Water Chestnut (Singhara)', category: 'vegetables', calories: 60, serving: '½ cup', protein: 0.9, carbs: 14.8, fat: 0.1 },
  { name: 'Yam (Suran, cooked)', category: 'vegetables', calories: 158, serving: '1 cup', protein: 2, carbs: 37, fat: 0.2 },
  { name: 'Lauki Sabzi (bottle gourd)', category: 'vegetables', calories: 90, serving: '1 katori', protein: 1.5, carbs: 8, fat: 5.5 },
  { name: 'Turai Sabzi (ridge gourd)', category: 'vegetables', calories: 85, serving: '1 katori', protein: 1.5, carbs: 8, fat: 5 },
  { name: 'Tinda Sabzi', category: 'vegetables', calories: 90, serving: '1 katori', protein: 1.6, carbs: 9, fat: 5 },
  { name: 'Karela Sabzi (bitter gourd)', category: 'vegetables', calories: 110, serving: '1 katori', protein: 2, carbs: 10, fat: 7 },
  { name: 'Parwal Sabzi (pointed gourd)', category: 'vegetables', calories: 100, serving: '1 katori', protein: 1.8, carbs: 9, fat: 6 },
  { name: 'Arbi Sabzi (colocasia)', category: 'vegetables', calories: 150, serving: '1 katori', protein: 2, carbs: 20, fat: 7 },
  { name: 'Cabbage Sabzi', category: 'vegetables', calories: 110, serving: '1 katori', protein: 2, carbs: 10, fat: 7 },
  { name: 'Beans Poriyal', category: 'vegetables', calories: 120, serving: '1 katori', protein: 3, carbs: 10, fat: 7.5 },
  { name: 'Cabbage Thoran', category: 'vegetables', calories: 130, serving: '1 katori', protein: 3, carbs: 10, fat: 8.5 },
  { name: 'Avial', category: 'vegetables', calories: 160, serving: '1 katori', protein: 3, carbs: 12, fat: 11 },
  { name: 'Aloo Matar', category: 'vegetables', calories: 180, serving: '1 katori', protein: 4.5, carbs: 24, fat: 7.5 },
  { name: 'Aloo Methi', category: 'vegetables', calories: 170, serving: '1 katori', protein: 3.5, carbs: 18, fat: 9 },
  { name: 'Aloo Jeera', category: 'vegetables', calories: 180, serving: '1 katori', protein: 3, carbs: 26, fat: 7.5 },
  { name: 'Dum Aloo', category: 'vegetables', calories: 230, serving: '1 katori', protein: 4, carbs: 26, fat: 12 },
  { name: 'Gajar Matar Sabzi', category: 'vegetables', calories: 140, serving: '1 katori', protein: 3, carbs: 15, fat: 7.5 },
  { name: 'Kaddu Sabzi (pumpkin)', category: 'vegetables', calories: 120, serving: '1 katori', protein: 1.8, carbs: 16, fat: 5.5 },
  { name: 'Mixed Veg Sabzi', category: 'vegetables', calories: 145, serving: '1 katori', protein: 3.5, carbs: 14, fat: 8.5 },
  { name: 'Sarson ka Saag', category: 'vegetables', calories: 160, serving: '1 katori', protein: 5, carbs: 10, fat: 11 },
  { name: 'Capsicum Sabzi', category: 'vegetables', calories: 130, serving: '1 katori', protein: 2, carbs: 11, fat: 8.5 },
  { name: 'Stuffed Capsicum', category: 'vegetables', calories: 190, serving: '1 piece', protein: 4, carbs: 18, fat: 11 },
  { name: 'Veg Jalfrezi', category: 'vegetables', calories: 180, serving: '1 katori', protein: 4, carbs: 16, fat: 11 },
  { name: 'Lauki Kofta Curry', category: 'vegetables', calories: 240, serving: '1 katori', protein: 4, carbs: 18, fat: 17 },
  { name: 'Raw Banana Sabzi', category: 'vegetables', calories: 160, serving: '1 katori', protein: 2, carbs: 24, fat: 6.5 },

  // ── Grains & breads ─────────────────────────────────────────────────────
  { name: 'White Rice (cooked)', category: 'grains', calories: 205, serving: '1 cup', protein: 4.3, carbs: 45, fat: 0.4 },
  { name: 'Brown Rice (cooked)', category: 'grains', calories: 218, serving: '1 cup', protein: 4.5, carbs: 46, fat: 1.6 },
  { name: 'Chapati / Roti', category: 'grains', calories: 104, serving: '1 medium', protein: 3.5, carbs: 18, fat: 2.5 },
  { name: 'Paratha (plain)', category: 'grains', calories: 260, serving: '1 medium', protein: 5, carbs: 30, fat: 13 },
  { name: 'Aloo Paratha', category: 'grains', calories: 300, serving: '1 medium', protein: 6, carbs: 40, fat: 13 },
  { name: 'Naan', category: 'grains', calories: 262, serving: '1 piece', protein: 9, carbs: 45, fat: 5 },
  { name: 'White Bread', category: 'grains', calories: 75, serving: '1 slice', protein: 2.6, carbs: 14, fat: 1 },
  { name: 'Whole Wheat Bread', category: 'grains', calories: 81, serving: '1 slice', protein: 4, carbs: 14, fat: 1.1 },
  { name: 'Oats (cooked)', category: 'grains', calories: 166, serving: '1 cup', protein: 5.9, carbs: 28, fat: 3.6 },
  { name: 'Muesli', category: 'grains', calories: 289, serving: '⅔ cup', protein: 8, carbs: 66, fat: 4 },
  { name: 'Cornflakes + Milk', category: 'grains', calories: 220, serving: '1 bowl', protein: 8, carbs: 40, fat: 3.5 },
  { name: 'Pasta (cooked)', category: 'grains', calories: 220, serving: '1 cup', protein: 8, carbs: 43, fat: 1.3 },
  { name: 'Quinoa (cooked)', category: 'grains', calories: 222, serving: '1 cup', protein: 8.1, carbs: 39, fat: 3.6 },
  { name: 'Poha', category: 'grains', calories: 250, serving: '1 plate', protein: 5, carbs: 45, fat: 6 },
  { name: 'Upma', category: 'grains', calories: 230, serving: '1 katori', protein: 6, carbs: 36, fat: 7 },
  { name: 'Idli', category: 'grains', calories: 58, serving: '1 piece', protein: 2, carbs: 12, fat: 0.4 },
  { name: 'Dosa (plain)', category: 'grains', calories: 168, serving: '1 medium', protein: 4, carbs: 28, fat: 4 },
  { name: 'Masala Dosa', category: 'grains', calories: 387, serving: '1 dosa', protein: 7, carbs: 60, fat: 13 },
  { name: 'Uttapam', category: 'grains', calories: 210, serving: '1 piece', protein: 5, carbs: 35, fat: 5.5 },
  { name: 'Tortilla / Wrap', category: 'grains', calories: 140, serving: '1 (8 in)', protein: 4, carbs: 24, fat: 3.5 },
  { name: 'Methi Thepla', category: 'grains', calories: 120, serving: '1 piece', protein: 3, carbs: 16, fat: 5 },
  { name: 'Rava Dosa', category: 'grains', calories: 220, serving: '1 dosa', protein: 4, carbs: 30, fat: 9 },
  { name: 'Pesarattu', category: 'grains', calories: 200, serving: '1 dosa', protein: 10, carbs: 28, fat: 5.5 },
  { name: 'Appam', category: 'grains', calories: 120, serving: '1 piece', protein: 2, carbs: 23, fat: 2 },
  { name: 'Puttu', category: 'grains', calories: 200, serving: '1 serving', protein: 4, carbs: 40, fat: 2.5 },
  { name: 'Idiyappam', category: 'grains', calories: 130, serving: '2 pieces', protein: 2.5, carbs: 28, fat: 0.5 },
  { name: 'Neer Dosa', category: 'grains', calories: 90, serving: '2 pieces', protein: 1.5, carbs: 17, fat: 1.5 },
  { name: 'Set Dosa', category: 'grains', calories: 180, serving: '2 pieces', protein: 4, carbs: 30, fat: 4.5 },
  { name: 'Adai', category: 'grains', calories: 220, serving: '1 piece', protein: 10, carbs: 30, fat: 7 },
  { name: 'Appe (Paniyaram)', category: 'grains', calories: 180, serving: '4 pieces', protein: 4, carbs: 26, fat: 6.5 },
  { name: 'Akki Roti', category: 'grains', calories: 200, serving: '1 roti', protein: 4, carbs: 32, fat: 6 },
  { name: 'Thalipeeth', category: 'grains', calories: 180, serving: '1 piece', protein: 6, carbs: 26, fat: 6 },
  { name: 'Ragi Mudde', category: 'grains', calories: 140, serving: '1 ball', protein: 3, carbs: 30, fat: 0.5 },
  { name: 'Ragi Dosa', category: 'grains', calories: 150, serving: '1 dosa', protein: 3.5, carbs: 24, fat: 4 },
  { name: 'Jowar Roti', category: 'grains', calories: 110, serving: '1 roti', protein: 3, carbs: 22, fat: 1 },
  { name: 'Bajra Roti', category: 'grains', calories: 120, serving: '1 roti', protein: 3.5, carbs: 22, fat: 2 },
  { name: 'Makki ki Roti', category: 'grains', calories: 180, serving: '1 roti', protein: 4, carbs: 30, fat: 5 },
  { name: 'Missi Roti', category: 'grains', calories: 130, serving: '1 roti', protein: 5, carbs: 20, fat: 3.5 },
  { name: 'Rumali Roti', category: 'grains', calories: 120, serving: '1 roti', protein: 3.5, carbs: 22, fat: 1.5 },
  { name: 'Tandoori Roti', category: 'grains', calories: 120, serving: '1 roti', protein: 4, carbs: 24, fat: 1 },
  { name: 'Butter Naan', category: 'grains', calories: 320, serving: '1 piece', protein: 9, carbs: 46, fat: 11 },
  { name: 'Garlic Naan', category: 'grains', calories: 300, serving: '1 piece', protein: 9, carbs: 45, fat: 9 },
  { name: 'Kulcha', category: 'grains', calories: 270, serving: '1 piece', protein: 8, carbs: 45, fat: 6.5 },
  { name: 'Bhatura', category: 'grains', calories: 330, serving: '1 piece', protein: 7, carbs: 40, fat: 15.5 },
  { name: 'Puri', category: 'grains', calories: 130, serving: '1 piece', protein: 2, carbs: 15, fat: 6.5 },
  { name: 'Gobi Paratha', category: 'grains', calories: 270, serving: '1 paratha', protein: 6, carbs: 34, fat: 12 },
  { name: 'Paneer Paratha', category: 'grains', calories: 330, serving: '1 paratha', protein: 11, carbs: 36, fat: 16 },
  { name: 'Methi Paratha', category: 'grains', calories: 250, serving: '1 paratha', protein: 5.5, carbs: 32, fat: 11 },
  { name: 'Mooli Paratha', category: 'grains', calories: 260, serving: '1 paratha', protein: 5.5, carbs: 33, fat: 11.5 },
  { name: 'Lachha Paratha', category: 'grains', calories: 290, serving: '1 paratha', protein: 5.5, carbs: 35, fat: 14.5 },
  { name: 'Kerala Parotta', category: 'grains', calories: 350, serving: '1 piece', protein: 6, carbs: 42, fat: 17 },
  { name: 'Multigrain Bread', category: 'grains', calories: 85, serving: '1 slice', protein: 4.2, carbs: 14, fat: 1.4 },
  { name: 'Sourdough Bread', category: 'grains', calories: 130, serving: '1 slice', protein: 5, carbs: 25, fat: 0.8 },
  { name: 'Bagel', category: 'grains', calories: 280, serving: '1 bagel', protein: 11, carbs: 55, fat: 1.5 },
  { name: 'Croissant', category: 'grains', calories: 230, serving: '1 medium', protein: 4.7, carbs: 26, fat: 12 },
  { name: 'Pita Bread', category: 'grains', calories: 165, serving: '1 piece', protein: 5.5, carbs: 33, fat: 0.7 },
  { name: 'Garlic Bread', category: 'grains', calories: 180, serving: '2 slices', protein: 4, carbs: 21, fat: 9 },
  { name: 'Pav Bun', category: 'grains', calories: 150, serving: '1 bun', protein: 4.5, carbs: 27, fat: 2.5 },
  { name: 'Buttered Toast', category: 'grains', calories: 155, serving: '1 slice', protein: 2.7, carbs: 14, fat: 9 },
  { name: 'Sabudana Khichdi', category: 'grains', calories: 350, serving: '1 plate', protein: 4, carbs: 50, fat: 15 },
  { name: 'Semiya Upma', category: 'grains', calories: 220, serving: '1 katori', protein: 5, carbs: 35, fat: 6.5 },
  { name: 'Daliya Porridge', category: 'grains', calories: 170, serving: '1 katori', protein: 5.5, carbs: 30, fat: 3 },
  { name: 'Foxtail Millet (cooked)', category: 'grains', calories: 190, serving: '1 cup', protein: 5, carbs: 40, fat: 1.8 },
  { name: 'Couscous (cooked)', category: 'grains', calories: 176, serving: '1 cup', protein: 6, carbs: 36, fat: 0.3 },
  { name: 'Barley (cooked)', category: 'grains', calories: 193, serving: '1 cup', protein: 3.5, carbs: 44, fat: 0.7 },
  { name: 'Buckwheat (cooked)', category: 'grains', calories: 155, serving: '1 cup', protein: 5.7, carbs: 33, fat: 1 },
  { name: 'Murmura (puffed rice)', category: 'grains', calories: 54, serving: '1 cup', protein: 1, carbs: 12, fat: 0.1 },
  { name: 'Overnight Oats', category: 'grains', calories: 350, serving: '1 jar', protein: 14, carbs: 52, fat: 10 },
  { name: 'Granola', category: 'grains', calories: 200, serving: '½ cup', protein: 4.5, carbs: 27, fat: 8 },
  { name: 'Wheat Flakes + Milk', category: 'grains', calories: 210, serving: '1 bowl', protein: 8, carbs: 38, fat: 3 },
  { name: 'Chocos + Milk', category: 'grains', calories: 230, serving: '1 bowl', protein: 7, carbs: 43, fat: 3.5 },
  { name: 'Jeera Rice', category: 'grains', calories: 250, serving: '1 katori', protein: 4, carbs: 40, fat: 8 },

  // ── Protein ─────────────────────────────────────────────────────────────
  { name: 'Egg (boiled)', category: 'protein', calories: 78, serving: '1 large', protein: 6.3, carbs: 0.6, fat: 5.3 },
  { name: 'Egg Omelette (2 eggs)', category: 'protein', calories: 220, serving: '1 omelette', protein: 13, carbs: 2, fat: 17 },
  { name: 'Chicken Breast (grilled)', category: 'protein', calories: 165, serving: '100 g', protein: 31, carbs: 0, fat: 3.6 },
  { name: 'Chicken Curry', category: 'protein', calories: 280, serving: '1 katori', protein: 22, carbs: 8, fat: 17 },
  { name: 'Tandoori Chicken', category: 'protein', calories: 260, serving: '2 pieces', protein: 30, carbs: 5, fat: 13 },
  { name: 'Fish (grilled)', category: 'protein', calories: 180, serving: '150 g', protein: 30, carbs: 0, fat: 6 },
  { name: 'Fish Curry', category: 'protein', calories: 240, serving: '1 katori', protein: 20, carbs: 7, fat: 14 },
  { name: 'Prawns (sautéed)', category: 'protein', calories: 120, serving: '100 g', protein: 24, carbs: 0.2, fat: 1.7 },
  { name: 'Mutton Curry', category: 'protein', calories: 330, serving: '1 katori', protein: 24, carbs: 6, fat: 23 },
  { name: 'Paneer (raw)', category: 'protein', calories: 265, serving: '100 g', protein: 18, carbs: 1.2, fat: 21 },
  { name: 'Paneer Butter Masala', category: 'protein', calories: 350, serving: '1 katori', protein: 12, carbs: 12, fat: 28 },
  { name: 'Palak Paneer', category: 'protein', calories: 280, serving: '1 katori', protein: 13, carbs: 9, fat: 21 },
  { name: 'Tofu', category: 'protein', calories: 94, serving: '100 g', protein: 10, carbs: 2.3, fat: 5.9 },
  { name: 'Dal (cooked)', category: 'protein', calories: 150, serving: '1 katori', protein: 9, carbs: 22, fat: 3 },
  { name: 'Dal Makhani', category: 'protein', calories: 280, serving: '1 katori', protein: 11, carbs: 24, fat: 16 },
  { name: 'Chole (chickpea curry)', category: 'protein', calories: 240, serving: '1 katori', protein: 11, carbs: 32, fat: 8 },
  { name: 'Rajma (kidney bean curry)', category: 'protein', calories: 220, serving: '1 katori', protein: 11, carbs: 30, fat: 6 },
  { name: 'Sprouts Salad', category: 'protein', calories: 120, serving: '1 katori', protein: 8, carbs: 18, fat: 1.5 },
  { name: 'Whey Protein Shake', category: 'protein', calories: 130, serving: '1 scoop + water', protein: 25, carbs: 3, fat: 1.5 },
  { name: 'Peanut Butter', category: 'protein', calories: 94, serving: '1 tbsp', protein: 4, carbs: 3, fat: 8 },
  { name: 'Almonds', category: 'protein', calories: 164, serving: '23 nuts (28 g)', protein: 6, carbs: 6, fat: 14 },
  { name: 'Walnuts', category: 'protein', calories: 185, serving: '7 halves (28 g)', protein: 4.3, carbs: 3.9, fat: 18.5 },
  { name: 'Cashews', category: 'protein', calories: 157, serving: '18 nuts (28 g)', protein: 5.2, carbs: 8.6, fat: 12.4 },
  { name: 'Moong Dal (cooked)', category: 'protein', calories: 147, serving: '1 katori', protein: 10, carbs: 25, fat: 0.8 },
  { name: 'Masoor Dal (cooked)', category: 'protein', calories: 150, serving: '1 katori', protein: 10, carbs: 24, fat: 1.5 },
  { name: 'Toor Dal (cooked)', category: 'protein', calories: 160, serving: '1 katori', protein: 9, carbs: 26, fat: 2.5 },
  { name: 'Chana Dal (cooked)', category: 'protein', calories: 180, serving: '1 katori', protein: 10, carbs: 28, fat: 3.5 },
  { name: 'Urad Dal (cooked)', category: 'protein', calories: 170, serving: '1 katori', protein: 10, carbs: 26, fat: 3 },
  { name: 'Dal Tadka', category: 'protein', calories: 210, serving: '1 katori', protein: 9, carbs: 24, fat: 9 },
  { name: 'Dal Fry', category: 'protein', calories: 220, serving: '1 katori', protein: 9, carbs: 25, fat: 10 },
  { name: 'Panchmel Dal', category: 'protein', calories: 190, serving: '1 katori', protein: 10, carbs: 26, fat: 5.5 },
  { name: 'Sambar', category: 'protein', calories: 130, serving: '1 katori', protein: 5, carbs: 18, fat: 4 },
  { name: 'Rasam', category: 'protein', calories: 60, serving: '1 katori', protein: 1.5, carbs: 9, fat: 2 },
  { name: 'Kadhi', category: 'protein', calories: 160, serving: '1 katori', protein: 6, carbs: 12, fat: 10 },
  { name: 'Lobia Curry (black-eyed peas)', category: 'protein', calories: 200, serving: '1 katori', protein: 10, carbs: 28, fat: 5.5 },
  { name: 'Boiled Chana', category: 'protein', calories: 180, serving: '1 katori', protein: 9.5, carbs: 30, fat: 3 },
  { name: 'Edamame', category: 'protein', calories: 188, serving: '1 cup', protein: 18, carbs: 14, fat: 8 },
  { name: 'Soya Chunks (cooked)', category: 'protein', calories: 170, serving: '1 katori (50 g dry)', protein: 26, carbs: 15, fat: 0.5 },
  { name: 'Soya Chunk Curry', category: 'protein', calories: 220, serving: '1 katori', protein: 18, carbs: 14, fat: 10 },
  { name: 'Tofu Bhurji', category: 'protein', calories: 180, serving: '1 katori', protein: 14, carbs: 6, fat: 12 },
  { name: 'Paneer Tikka', category: 'protein', calories: 280, serving: '6 pieces', protein: 18, carbs: 8, fat: 19.5 },
  { name: 'Paneer Bhurji', category: 'protein', calories: 290, serving: '1 katori', protein: 14, carbs: 7, fat: 23 },
  { name: 'Shahi Paneer', category: 'protein', calories: 360, serving: '1 katori', protein: 12, carbs: 14, fat: 28 },
  { name: 'Matar Paneer', category: 'protein', calories: 270, serving: '1 katori', protein: 12, carbs: 16, fat: 17.5 },
  { name: 'Kadai Paneer', category: 'protein', calories: 300, serving: '1 katori', protein: 13, carbs: 11, fat: 23 },
  { name: 'Chilli Paneer', category: 'protein', calories: 320, serving: '1 plate', protein: 14, carbs: 20, fat: 20.5 },
  { name: 'Egg Curry', category: 'protein', calories: 250, serving: '1 katori (2 eggs)', protein: 14, carbs: 8, fat: 18 },
  { name: 'Egg Bhurji', category: 'protein', calories: 200, serving: '2 eggs', protein: 12, carbs: 4, fat: 15 },
  { name: 'Scrambled Eggs', category: 'protein', calories: 180, serving: '2 eggs', protein: 12, carbs: 2, fat: 13.5 },
  { name: 'Fried Egg', category: 'protein', calories: 90, serving: '1 egg', protein: 6.3, carbs: 0.4, fat: 7 },
  { name: 'Egg Whites', category: 'protein', calories: 51, serving: '3 whites', protein: 10.8, carbs: 0.7, fat: 0.2 },
  { name: 'Chicken 65', category: 'protein', calories: 290, serving: '6 pieces (150 g)', protein: 22, carbs: 12, fat: 17 },
  { name: 'Chicken Tikka', category: 'protein', calories: 220, serving: '6 pieces', protein: 28, carbs: 4, fat: 10 },
  { name: 'Butter Chicken', category: 'protein', calories: 400, serving: '1 katori', protein: 24, carbs: 10, fat: 29 },
  { name: 'Chicken Korma', category: 'protein', calories: 350, serving: '1 katori', protein: 22, carbs: 9, fat: 25 },
  { name: 'Kadai Chicken', category: 'protein', calories: 300, serving: '1 katori', protein: 25, carbs: 8, fat: 19 },
  { name: 'Chicken Keema', category: 'protein', calories: 280, serving: '1 katori', protein: 22, carbs: 6, fat: 19 },
  { name: 'Chicken Drumstick (roasted)', category: 'protein', calories: 150, serving: '1 piece', protein: 17, carbs: 0, fat: 8.5 },
  { name: 'Chicken Thigh (grilled)', category: 'protein', calories: 210, serving: '100 g', protein: 26, carbs: 0, fat: 11 },
  { name: 'Chicken Sausage', category: 'protein', calories: 110, serving: '1 link', protein: 7, carbs: 2, fat: 8 },
  { name: 'Salami', category: 'protein', calories: 110, serving: '4 slices', protein: 6, carbs: 1, fat: 9.5 },
  { name: 'Bacon', category: 'protein', calories: 90, serving: '2 strips', protein: 6, carbs: 0.3, fat: 7 },
  { name: 'Ham', category: 'protein', calories: 60, serving: '2 slices', protein: 9, carbs: 1.5, fat: 2 },
  { name: 'Turkey Breast (sliced)', category: 'protein', calories: 60, serving: '3 slices', protein: 11, carbs: 1.5, fat: 1 },
  { name: 'Mutton Keema', category: 'protein', calories: 320, serving: '1 katori', protein: 22, carbs: 5, fat: 23.5 },
  { name: 'Mutton Rogan Josh', category: 'protein', calories: 360, serving: '1 katori', protein: 25, carbs: 7, fat: 25.5 },
  { name: 'Pork Chop (grilled)', category: 'protein', calories: 230, serving: '1 chop', protein: 26, carbs: 0, fat: 13.5 },
  { name: 'Salmon (grilled)', category: 'protein', calories: 230, serving: '1 fillet (110 g)', protein: 25, carbs: 0, fat: 14 },
  { name: 'Tuna (canned in water)', category: 'protein', calories: 100, serving: '1 can (85 g drained)', protein: 20, carbs: 0, fat: 1 },
  { name: 'Fish Fry', category: 'protein', calories: 250, serving: '1 piece (120 g)', protein: 20, carbs: 8, fat: 15 },
  { name: 'Fish Tikka', category: 'protein', calories: 200, serving: '6 pieces', protein: 26, carbs: 4, fat: 9 },
  { name: 'Prawn Curry', category: 'protein', calories: 230, serving: '1 katori', protein: 18, carbs: 7, fat: 14.5 },
  { name: 'Crab (steamed)', category: 'protein', calories: 98, serving: '100 g', protein: 20, carbs: 0, fat: 1.5 },
  { name: 'Seekh Kebab', category: 'protein', calories: 270, serving: '2 kebabs', protein: 18, carbs: 6, fat: 19 },
  { name: 'Shami Kebab', category: 'protein', calories: 200, serving: '2 pieces', protein: 12, carbs: 10, fat: 12 },
  { name: 'Hara Bhara Kebab', category: 'protein', calories: 180, serving: '3 pieces', protein: 5, carbs: 22, fat: 8 },
  { name: 'Pistachios', category: 'protein', calories: 159, serving: '49 nuts (28 g)', protein: 5.7, carbs: 7.7, fat: 12.9 },
  { name: 'Peanuts (roasted)', category: 'protein', calories: 166, serving: '28 g', protein: 6.7, carbs: 6, fat: 14 },
  { name: 'Mixed Nuts', category: 'protein', calories: 170, serving: '28 g', protein: 5, carbs: 7, fat: 15 },
  { name: 'Pumpkin Seeds', category: 'protein', calories: 158, serving: '28 g', protein: 8.5, carbs: 3, fat: 14 },
  { name: 'Sunflower Seeds', category: 'protein', calories: 165, serving: '28 g', protein: 5.5, carbs: 6.5, fat: 14 },
  { name: 'Chia Seeds', category: 'protein', calories: 138, serving: '2 tbsp (28 g)', protein: 4.7, carbs: 12, fat: 8.7 },
  { name: 'Flax Seeds', category: 'protein', calories: 75, serving: '2 tbsp', protein: 2.6, carbs: 4, fat: 6 },
  { name: 'Almond Butter', category: 'protein', calories: 98, serving: '1 tbsp', protein: 3.4, carbs: 3, fat: 8.9 },
  { name: 'Hummus', category: 'protein', calories: 70, serving: '¼ cup', protein: 2, carbs: 6, fat: 5 },
  { name: 'Protein Shake (with milk)', category: 'protein', calories: 280, serving: '1 scoop + milk', protein: 33, carbs: 15, fat: 8 },
  { name: 'Plant Protein Shake', category: 'protein', calories: 140, serving: '1 scoop + water', protein: 21, carbs: 8, fat: 2.5 },
  { name: 'Mass Gainer Shake', category: 'protein', calories: 600, serving: '1 serving + milk', protein: 30, carbs: 100, fat: 10 },

  // ── Dairy ───────────────────────────────────────────────────────────────
  { name: 'Milk (whole)', category: 'dairy', calories: 149, serving: '1 cup', protein: 7.7, carbs: 12, fat: 8 },
  { name: 'Milk (toned/2%)', category: 'dairy', calories: 122, serving: '1 cup', protein: 8.1, carbs: 12, fat: 4.8 },
  { name: 'Curd / Dahi', category: 'dairy', calories: 98, serving: '1 katori', protein: 5.5, carbs: 7, fat: 5 },
  { name: 'Greek Yogurt (plain)', category: 'dairy', calories: 100, serving: '170 g', protein: 17, carbs: 6, fat: 0.7 },
  { name: 'Buttermilk / Chaas', category: 'dairy', calories: 40, serving: '1 glass', protein: 2.5, carbs: 4, fat: 1.5 },
  { name: 'Lassi (sweet)', category: 'dairy', calories: 180, serving: '1 glass', protein: 5, carbs: 27, fat: 6 },
  { name: 'Cheese (cheddar)', category: 'dairy', calories: 113, serving: '1 slice (28 g)', protein: 6.4, carbs: 0.9, fat: 9.3 },
  { name: 'Butter', category: 'dairy', calories: 102, serving: '1 tbsp', protein: 0.1, carbs: 0, fat: 11.5 },
  { name: 'Ghee', category: 'dairy', calories: 112, serving: '1 tbsp', protein: 0, carbs: 0, fat: 12.7 },
  { name: 'Milk (skim)', category: 'dairy', calories: 83, serving: '1 cup', protein: 8.3, carbs: 12, fat: 0.2 },
  { name: 'Almond Milk (unsweetened)', category: 'dairy', calories: 30, serving: '1 cup', protein: 1, carbs: 1, fat: 2.5 },
  { name: 'Soy Milk', category: 'dairy', calories: 80, serving: '1 cup', protein: 7, carbs: 4, fat: 4 },
  { name: 'Oat Milk', category: 'dairy', calories: 120, serving: '1 cup', protein: 3, carbs: 16, fat: 5 },
  { name: 'Mozzarella Cheese', category: 'dairy', calories: 85, serving: '28 g', protein: 6.3, carbs: 0.6, fat: 6.3 },
  { name: 'Cottage Cheese (low-fat)', category: 'dairy', calories: 81, serving: '½ cup', protein: 14, carbs: 3, fat: 1.2 },
  { name: 'Cream Cheese', category: 'dairy', calories: 100, serving: '2 tbsp', protein: 1.8, carbs: 1.6, fat: 9.8 },
  { name: 'Fruit Yogurt', category: 'dairy', calories: 150, serving: '1 cup', protein: 6, carbs: 26, fat: 2 },
  { name: 'Mishti Doi', category: 'dairy', calories: 220, serving: '1 katori', protein: 6, carbs: 34, fat: 7 },
  { name: 'Shrikhand', category: 'dairy', calories: 280, serving: '1 katori', protein: 7, carbs: 40, fat: 10 },
  { name: 'Lassi (salted)', category: 'dairy', calories: 90, serving: '1 glass', protein: 4, carbs: 7, fat: 5 },
  { name: 'Mango Lassi', category: 'dairy', calories: 230, serving: '1 glass', protein: 6, carbs: 38, fat: 6 },
  { name: 'Malai (fresh cream)', category: 'dairy', calories: 100, serving: '2 tbsp', protein: 0.8, carbs: 1.6, fat: 10 },
  { name: 'Condensed Milk', category: 'dairy', calories: 62, serving: '1 tbsp', protein: 1.5, carbs: 10.4, fat: 1.7 },
  { name: 'Khoya / Mawa', category: 'dairy', calories: 130, serving: '30 g', protein: 4.5, carbs: 7, fat: 9 },
  { name: 'Cheese Slice (processed)', category: 'dairy', calories: 60, serving: '1 slice', protein: 3.3, carbs: 1.5, fat: 4.5 },
  { name: 'Feta Cheese', category: 'dairy', calories: 75, serving: '28 g', protein: 4, carbs: 1.2, fat: 6 },
  { name: 'Parmesan Cheese', category: 'dairy', calories: 22, serving: '1 tbsp grated', protein: 1.9, carbs: 0.2, fat: 1.4 },
  { name: 'Milk Powder', category: 'dairy', calories: 33, serving: '1 tbsp', protein: 1.7, carbs: 2.5, fat: 1.7 },

  // ── Meals & dishes ──────────────────────────────────────────────────────
  { name: 'Veg Biryani', category: 'meals', calories: 400, serving: '1 plate', protein: 9, carbs: 65, fat: 12 },
  { name: 'Chicken Biryani', category: 'meals', calories: 490, serving: '1 plate', protein: 25, carbs: 60, fat: 16 },
  { name: 'Dal + Rice', category: 'meals', calories: 355, serving: '1 plate', protein: 13, carbs: 67, fat: 3.5 },
  { name: 'Rajma Chawal', category: 'meals', calories: 425, serving: '1 plate', protein: 15, carbs: 75, fat: 6.5 },
  { name: 'Curd Rice', category: 'meals', calories: 305, serving: '1 plate', protein: 9, carbs: 52, fat: 7 },
  { name: 'Khichdi', category: 'meals', calories: 280, serving: '1 plate', protein: 10, carbs: 48, fat: 5 },
  { name: 'Pulao', category: 'meals', calories: 350, serving: '1 plate', protein: 7, carbs: 58, fat: 10 },
  { name: 'Pav Bhaji', category: 'meals', calories: 400, serving: '1 plate (2 pav)', protein: 9, carbs: 55, fat: 16 },
  { name: 'Chole Bhature', category: 'meals', calories: 650, serving: '1 plate', protein: 16, carbs: 80, fat: 29 },
  { name: 'Thali (veg, standard)', category: 'meals', calories: 700, serving: '1 thali', protein: 20, carbs: 100, fat: 24 },
  { name: 'Fried Rice (veg)', category: 'meals', calories: 380, serving: '1 plate', protein: 7, carbs: 60, fat: 12 },
  { name: 'Noodles (hakka)', category: 'meals', calories: 420, serving: '1 plate', protein: 9, carbs: 62, fat: 15 },
  { name: 'Chicken Caesar Salad', category: 'meals', calories: 390, serving: '1 bowl', protein: 30, carbs: 12, fat: 25 },
  { name: 'Grilled Sandwich (veg)', category: 'meals', calories: 290, serving: '1 sandwich', protein: 9, carbs: 38, fat: 11 },
  { name: 'Egg Bhurji + 2 Roti', category: 'meals', calories: 420, serving: '1 plate', protein: 19, carbs: 40, fat: 20 },
  { name: 'Soup (mixed veg)', category: 'meals', calories: 90, serving: '1 bowl', protein: 3, carbs: 14, fat: 2.5 },
  { name: 'Litti Chokha', category: 'meals', calories: 400, serving: '2 litti + chokha', protein: 11, carbs: 60, fat: 13 },
  { name: 'Misal Pav', category: 'meals', calories: 450, serving: '1 plate', protein: 15, carbs: 55, fat: 19 },
  { name: 'Dabeli', category: 'meals', calories: 250, serving: '1 piece', protein: 5, carbs: 38, fat: 9 },
  { name: 'Kathi Roll (paneer)', category: 'meals', calories: 380, serving: '1 roll', protein: 13, carbs: 42, fat: 18 },
  { name: 'Kathi Roll (chicken)', category: 'meals', calories: 400, serving: '1 roll', protein: 22, carbs: 40, fat: 17 },
  { name: 'Malai Kofta', category: 'meals', calories: 330, serving: '1 katori', protein: 8, carbs: 20, fat: 24 },
  { name: 'Veg Korma', category: 'meals', calories: 240, serving: '1 katori', protein: 5, carbs: 18, fat: 16.5 },
  { name: 'Navratan Korma', category: 'meals', calories: 280, serving: '1 katori', protein: 6, carbs: 24, fat: 18 },
  { name: 'Veg Kolhapuri', category: 'meals', calories: 250, serving: '1 katori', protein: 6, carbs: 18, fat: 17 },
  { name: 'Mushroom Masala', category: 'meals', calories: 220, serving: '1 katori', protein: 6, carbs: 14, fat: 16 },
  { name: 'Kadhi Chawal', category: 'meals', calories: 330, serving: '1 plate', protein: 9, carbs: 50, fat: 10.5 },
  { name: 'Sambar Rice', category: 'meals', calories: 320, serving: '1 plate', protein: 9, carbs: 55, fat: 7 },
  { name: 'Lemon Rice', category: 'meals', calories: 280, serving: '1 plate', protein: 5, carbs: 45, fat: 9 },
  { name: 'Tamarind Rice', category: 'meals', calories: 290, serving: '1 plate', protein: 5, carbs: 48, fat: 9 },
  { name: 'Bisi Bele Bath', category: 'meals', calories: 350, serving: '1 plate', protein: 10, carbs: 55, fat: 10 },
  { name: 'Pongal', category: 'meals', calories: 300, serving: '1 plate', protein: 8, carbs: 45, fat: 9.5 },
  { name: 'Idli Sambar', category: 'meals', calories: 250, serving: '2 idli + sambar', protein: 8, carbs: 45, fat: 4 },
  { name: 'Vada Sambar', category: 'meals', calories: 320, serving: '2 vada + sambar', protein: 9, carbs: 34, fat: 17 },
  { name: 'Mutton Biryani', category: 'meals', calories: 550, serving: '1 plate', protein: 24, carbs: 60, fat: 24 },
  { name: 'Egg Biryani', category: 'meals', calories: 450, serving: '1 plate', protein: 16, carbs: 60, fat: 16 },
  { name: 'Aloo Puri', category: 'meals', calories: 480, serving: '1 plate (4 puri)', protein: 9, carbs: 60, fat: 23 },
  { name: 'Dal Baati Churma', category: 'meals', calories: 550, serving: '1 plate', protein: 13, carbs: 70, fat: 25 },
  { name: 'Undhiyu', category: 'meals', calories: 280, serving: '1 katori', protein: 6, carbs: 26, fat: 17 },
  { name: 'Tawa Pulao', category: 'meals', calories: 350, serving: '1 plate', protein: 7, carbs: 52, fat: 12.5 },
  { name: 'Chicken Fried Rice', category: 'meals', calories: 430, serving: '1 plate', protein: 18, carbs: 58, fat: 13 },
  { name: 'Egg Fried Rice', category: 'meals', calories: 410, serving: '1 plate', protein: 13, carbs: 58, fat: 13 },
  { name: 'Veg Manchurian (gravy)', category: 'meals', calories: 270, serving: '1 katori', protein: 5, carbs: 28, fat: 15 },
  { name: 'Chilli Chicken', category: 'meals', calories: 330, serving: '1 plate', protein: 24, carbs: 18, fat: 17.5 },
  { name: 'Schezwan Noodles', category: 'meals', calories: 450, serving: '1 plate', protein: 9, carbs: 64, fat: 17 },
  { name: 'Thukpa', category: 'meals', calories: 320, serving: '1 bowl', protein: 14, carbs: 45, fat: 9 },
  { name: 'Spaghetti Aglio e Olio', category: 'meals', calories: 430, serving: '1 plate', protein: 10, carbs: 56, fat: 18 },
  { name: 'Pasta Alfredo', category: 'meals', calories: 550, serving: '1 plate', protein: 15, carbs: 55, fat: 29.5 },
  { name: 'Pasta Arrabbiata', category: 'meals', calories: 400, serving: '1 plate', protein: 11, carbs: 62, fat: 11.5 },
  { name: 'Mac and Cheese', category: 'meals', calories: 420, serving: '1 bowl', protein: 15, carbs: 42, fat: 21 },
  { name: 'Lasagna (veg)', category: 'meals', calories: 380, serving: '1 piece', protein: 16, carbs: 38, fat: 18 },
  { name: 'Risotto (mushroom)', category: 'meals', calories: 420, serving: '1 plate', protein: 9, carbs: 56, fat: 17 },
  { name: 'Burrito Bowl (chicken)', category: 'meals', calories: 620, serving: '1 bowl', protein: 35, carbs: 65, fat: 23 },
  { name: 'Quesadilla (cheese)', category: 'meals', calories: 470, serving: '1 whole', protein: 18, carbs: 39, fat: 27 },
  { name: 'Pad Thai (chicken)', category: 'meals', calories: 570, serving: '1 plate', protein: 25, carbs: 65, fat: 23 },
  { name: 'Thai Green Curry (chicken)', category: 'meals', calories: 380, serving: '1 bowl', protein: 20, carbs: 12, fat: 27.5 },
  { name: 'Ramen (chicken)', category: 'meals', calories: 450, serving: '1 bowl', protein: 22, carbs: 55, fat: 15 },
  { name: 'Teriyaki Chicken with Rice', category: 'meals', calories: 580, serving: '1 bowl', protein: 32, carbs: 75, fat: 15 },
  { name: 'Bibimbap', category: 'meals', calories: 500, serving: '1 bowl', protein: 20, carbs: 70, fat: 15 },
  { name: 'Poke Bowl (salmon)', category: 'meals', calories: 550, serving: '1 bowl', protein: 28, carbs: 60, fat: 21 },
  { name: 'Falafel Wrap', category: 'meals', calories: 480, serving: '1 wrap', protein: 14, carbs: 58, fat: 21 },
  { name: 'Shakshuka', category: 'meals', calories: 300, serving: '1 pan (2 eggs)', protein: 15, carbs: 14, fat: 20 },
  { name: 'Chicken Stew', category: 'meals', calories: 280, serving: '1 bowl', protein: 20, carbs: 14, fat: 15.5 },
  { name: 'Veg Stew (Kerala)', category: 'meals', calories: 220, serving: '1 katori', protein: 4, carbs: 16, fat: 15.5 },
  { name: 'Tomato Soup', category: 'meals', calories: 90, serving: '1 bowl', protein: 2, carbs: 16, fat: 2 },
  { name: 'Chicken Soup', category: 'meals', calories: 130, serving: '1 bowl', protein: 12, carbs: 9, fat: 4.5 },
  { name: 'Sweet Corn Soup', category: 'meals', calories: 120, serving: '1 bowl', protein: 3, carbs: 20, fat: 3 },
  { name: 'Manchow Soup', category: 'meals', calories: 150, serving: '1 bowl', protein: 4, carbs: 18, fat: 7 },
  { name: 'Greek Salad', category: 'meals', calories: 210, serving: '1 bowl', protein: 6, carbs: 12, fat: 15.5 },
  { name: 'Quinoa Salad', category: 'meals', calories: 320, serving: '1 bowl', protein: 10, carbs: 40, fat: 13.5 },
  { name: 'Club Sandwich', category: 'meals', calories: 460, serving: '1 sandwich', protein: 22, carbs: 42, fat: 22 },
  { name: 'Chicken Wrap (grilled)', category: 'meals', calories: 420, serving: '1 wrap', protein: 26, carbs: 40, fat: 17 },

  // ── Snacks & sweets ─────────────────────────────────────────────────────
  { name: 'Samosa', category: 'snacks', calories: 262, serving: '1 piece', protein: 4, carbs: 30, fat: 14 },
  { name: 'Vada Pav', category: 'snacks', calories: 290, serving: '1 piece', protein: 6, carbs: 40, fat: 12 },
  { name: 'Pakora (mixed)', category: 'snacks', calories: 180, serving: '4 pieces', protein: 4, carbs: 16, fat: 11 },
  { name: 'Dhokla', category: 'snacks', calories: 160, serving: '2 pieces', protein: 6, carbs: 24, fat: 4.5 },
  { name: 'Bhel Puri', category: 'snacks', calories: 230, serving: '1 plate', protein: 5, carbs: 38, fat: 7 },
  { name: 'Popcorn (plain)', category: 'snacks', calories: 93, serving: '3 cups', protein: 3, carbs: 19, fat: 1.1 },
  { name: 'Potato Chips', category: 'snacks', calories: 160, serving: '1 small pack (30 g)', protein: 2, carbs: 15, fat: 10 },
  { name: 'Dark Chocolate', category: 'snacks', calories: 170, serving: '4 squares (28 g)', protein: 2.2, carbs: 13, fat: 12 },
  { name: 'Milk Chocolate Bar', category: 'snacks', calories: 235, serving: '1 bar (44 g)', protein: 3.4, carbs: 26, fat: 13 },
  { name: 'Biscuits (Marie)', category: 'snacks', calories: 112, serving: '4 biscuits', protein: 1.6, carbs: 19, fat: 3.2 },
  { name: 'Cookies (chocolate chip)', category: 'snacks', calories: 160, serving: '2 cookies', protein: 1.8, carbs: 22, fat: 8 },
  { name: 'Granola Bar', category: 'snacks', calories: 120, serving: '1 bar', protein: 2.5, carbs: 20, fat: 4 },
  { name: 'Protein Bar', category: 'snacks', calories: 200, serving: '1 bar', protein: 20, carbs: 21, fat: 7 },
  { name: 'Gulab Jamun', category: 'snacks', calories: 150, serving: '1 piece', protein: 2, carbs: 23, fat: 6 },
  { name: 'Jalebi', category: 'snacks', calories: 150, serving: '1 piece (30 g)', protein: 1, carbs: 22, fat: 6.5 },
  { name: 'Kheer', category: 'snacks', calories: 215, serving: '1 katori', protein: 6, carbs: 32, fat: 7 },
  { name: 'Ice Cream (vanilla)', category: 'snacks', calories: 137, serving: '1 scoop', protein: 2.3, carbs: 16, fat: 7.3 },
  { name: 'Cake (chocolate slice)', category: 'snacks', calories: 350, serving: '1 slice', protein: 5, carbs: 50, fat: 15 },
  { name: 'Trail Mix', category: 'snacks', calories: 170, serving: '¼ cup', protein: 5, carbs: 13, fat: 12 },
  { name: 'Banana Chips', category: 'snacks', calories: 150, serving: '30 g', protein: 0.7, carbs: 17, fat: 9 },
  { name: 'Kachori', category: 'snacks', calories: 190, serving: '1 piece', protein: 3.5, carbs: 20, fat: 11 },
  { name: 'Pani Puri', category: 'snacks', calories: 180, serving: '6 pieces', protein: 3, carbs: 30, fat: 5.5 },
  { name: 'Sev Puri', category: 'snacks', calories: 220, serving: '6 pieces', protein: 4, carbs: 28, fat: 10.5 },
  { name: 'Dahi Puri', category: 'snacks', calories: 240, serving: '6 pieces', protein: 6, carbs: 32, fat: 10 },
  { name: 'Papdi Chaat', category: 'snacks', calories: 280, serving: '1 plate', protein: 6, carbs: 34, fat: 13.5 },
  { name: 'Aloo Tikki', category: 'snacks', calories: 160, serving: '1 piece', protein: 2.5, carbs: 20, fat: 8 },
  { name: 'Aloo Tikki Chaat', category: 'snacks', calories: 320, serving: '1 plate', protein: 6, carbs: 38, fat: 16 },
  { name: 'Ragda Pattice', category: 'snacks', calories: 350, serving: '1 plate', protein: 10, carbs: 45, fat: 14.5 },
  { name: 'Dahi Vada', category: 'snacks', calories: 200, serving: '2 pieces', protein: 7, carbs: 24, fat: 8.5 },
  { name: 'Medu Vada', category: 'snacks', calories: 145, serving: '1 piece', protein: 3.5, carbs: 18, fat: 6.5 },
  { name: 'Sabudana Vada', category: 'snacks', calories: 220, serving: '2 pieces', protein: 3, carbs: 26, fat: 11.5 },
  { name: 'Batata Vada', category: 'snacks', calories: 180, serving: '1 piece', protein: 3.5, carbs: 22, fat: 9 },
  { name: 'Bread Pakora', category: 'snacks', calories: 220, serving: '1 piece', protein: 5, carbs: 24, fat: 11.5 },
  { name: 'Mirchi Bajji', category: 'snacks', calories: 150, serving: '2 pieces', protein: 2.5, carbs: 14, fat: 9.5 },
  { name: 'Murukku (Chakli)', category: 'snacks', calories: 150, serving: '2 pieces', protein: 2.5, carbs: 16, fat: 8.5 },
  { name: 'Mathri', category: 'snacks', calories: 130, serving: '2 pieces', protein: 2, carbs: 13, fat: 8 },
  { name: 'Khakhra', category: 'snacks', calories: 120, serving: '2 pieces', protein: 3.5, carbs: 18, fat: 3.5 },
  { name: 'Namkeen Mixture', category: 'snacks', calories: 160, serving: '30 g', protein: 4, carbs: 14, fat: 10 },
  { name: 'Aloo Bhujia', category: 'snacks', calories: 160, serving: '30 g', protein: 3.5, carbs: 15, fat: 10 },
  { name: 'Roasted Chana', category: 'snacks', calories: 120, serving: '¼ cup (30 g)', protein: 6, carbs: 18, fat: 1.8 },
  { name: 'Masala Peanuts', category: 'snacks', calories: 170, serving: '30 g', protein: 7, carbs: 8, fat: 12.5 },
  { name: 'Makhana (roasted)', category: 'snacks', calories: 106, serving: '1 cup (30 g)', protein: 3, carbs: 20, fat: 1.5 },
  { name: 'Peanut Chikki', category: 'snacks', calories: 130, serving: '1 piece (25 g)', protein: 4, carbs: 14, fat: 6.5 },
  { name: 'Til Ladoo', category: 'snacks', calories: 120, serving: '1 piece', protein: 2.5, carbs: 14, fat: 6 },
  { name: 'Besan Ladoo', category: 'snacks', calories: 180, serving: '1 piece', protein: 4, carbs: 18, fat: 10.5 },
  { name: 'Motichoor Ladoo', category: 'snacks', calories: 170, serving: '1 piece', protein: 2.5, carbs: 24, fat: 7.5 },
  { name: 'Rava Ladoo', category: 'snacks', calories: 160, serving: '1 piece', protein: 2, carbs: 22, fat: 7 },
  { name: 'Dates & Nut Ladoo', category: 'snacks', calories: 110, serving: '1 piece', protein: 2, carbs: 14, fat: 5.5 },
  { name: 'Kaju Katli', category: 'snacks', calories: 90, serving: '1 piece', protein: 1.7, carbs: 10, fat: 5 },
  { name: 'Barfi (khoya)', category: 'snacks', calories: 150, serving: '1 piece', protein: 3.5, carbs: 18, fat: 7 },
  { name: 'Coconut Barfi', category: 'snacks', calories: 160, serving: '1 piece', protein: 2, carbs: 20, fat: 8.5 },
  { name: 'Rasgulla', category: 'snacks', calories: 125, serving: '1 piece', protein: 2.5, carbs: 25, fat: 1 },
  { name: 'Rasmalai', category: 'snacks', calories: 210, serving: '1 piece', protein: 6, carbs: 22, fat: 11 },
  { name: 'Sandesh', category: 'snacks', calories: 100, serving: '1 piece', protein: 4, carbs: 14, fat: 3 },
  { name: 'Soan Papdi', category: 'snacks', calories: 150, serving: '1 piece (30 g)', protein: 2, carbs: 17, fat: 8 },
  { name: 'Mysore Pak', category: 'snacks', calories: 200, serving: '1 piece', protein: 2, carbs: 20, fat: 12.5 },
  { name: 'Modak (steamed)', category: 'snacks', calories: 120, serving: '1 piece', protein: 1.5, carbs: 20, fat: 4 },
  { name: 'Puran Poli', category: 'snacks', calories: 280, serving: '1 piece', protein: 6, carbs: 48, fat: 7 },
  { name: 'Gajar Halwa', category: 'snacks', calories: 250, serving: '1 katori', protein: 4, carbs: 32, fat: 12 },
  { name: 'Sooji Halwa', category: 'snacks', calories: 280, serving: '1 katori', protein: 3.5, carbs: 38, fat: 13 },
  { name: 'Moong Dal Halwa', category: 'snacks', calories: 320, serving: '1 katori', protein: 6, carbs: 36, fat: 17.5 },
  { name: 'Badam Halwa', category: 'snacks', calories: 350, serving: '1 katori', protein: 7, carbs: 34, fat: 21.5 },
  { name: 'Phirni', category: 'snacks', calories: 190, serving: '1 katori', protein: 5, carbs: 28, fat: 6.5 },
  { name: 'Shahi Tukda', category: 'snacks', calories: 360, serving: '1 piece', protein: 6, carbs: 42, fat: 18.5 },
  { name: 'Malpua', category: 'snacks', calories: 220, serving: '1 piece', protein: 3, carbs: 30, fat: 9.5 },
  { name: 'Balushahi', category: 'snacks', calories: 220, serving: '1 piece', protein: 2.5, carbs: 25, fat: 12.5 },
  { name: 'Petha', category: 'snacks', calories: 90, serving: '1 piece', protein: 0.2, carbs: 22, fat: 0.1 },
  { name: 'Kulfi', category: 'snacks', calories: 200, serving: '1 stick', protein: 5, carbs: 20, fat: 11.5 },
  { name: 'Cupcake', category: 'snacks', calories: 200, serving: '1 piece', protein: 2.5, carbs: 28, fat: 9 },
  { name: 'Brownie', category: 'snacks', calories: 230, serving: '1 piece', protein: 3, carbs: 30, fat: 11 },
  { name: 'Donut (glazed)', category: 'snacks', calories: 260, serving: '1 piece', protein: 4, carbs: 31, fat: 14 },
  { name: 'Muffin (blueberry)', category: 'snacks', calories: 380, serving: '1 large', protein: 6, carbs: 52, fat: 16.5 },
  { name: 'Cheesecake', category: 'snacks', calories: 400, serving: '1 slice', protein: 7, carbs: 32, fat: 27.5 },
  { name: 'Apple Pie', category: 'snacks', calories: 300, serving: '1 slice', protein: 2.5, carbs: 43, fat: 13.5 },
  { name: 'Tiramisu', category: 'snacks', calories: 350, serving: '1 piece', protein: 6, carbs: 35, fat: 20.5 },
  { name: 'Digestive Biscuits', category: 'snacks', calories: 140, serving: '3 biscuits', protein: 2, carbs: 20, fat: 6 },
  { name: 'Cream Biscuits', category: 'snacks', calories: 140, serving: '2 biscuits', protein: 1.5, carbs: 20, fat: 6 },
  { name: 'Rusk', category: 'snacks', calories: 90, serving: '2 pieces', protein: 2, carbs: 16, fat: 2 },
  { name: 'Khari (puff pastry)', category: 'snacks', calories: 170, serving: '2 pieces', protein: 2.5, carbs: 16, fat: 10.5 },
  { name: 'Salted Pretzels', category: 'snacks', calories: 110, serving: '28 g', protein: 2.6, carbs: 23, fat: 0.8 },
  { name: 'Tortilla Chips', category: 'snacks', calories: 140, serving: '28 g', protein: 2, carbs: 18, fat: 7 },
  { name: 'Cheese Popcorn', category: 'snacks', calories: 160, serving: '2 cups', protein: 2.5, carbs: 14, fat: 10.5 },
  { name: 'Tomato Ketchup', category: 'snacks', calories: 19, serving: '1 tbsp', protein: 0.2, carbs: 4.7, fat: 0 },
  { name: 'Mayonnaise', category: 'snacks', calories: 94, serving: '1 tbsp', protein: 0.1, carbs: 0.1, fat: 10 },
  { name: 'Coriander-Mint Chutney', category: 'snacks', calories: 15, serving: '1 tbsp', protein: 0.5, carbs: 2, fat: 0.5 },
  { name: 'Coconut Chutney', category: 'snacks', calories: 70, serving: '2 tbsp', protein: 1.5, carbs: 4, fat: 5.5 },
  { name: 'Tomato Chutney', category: 'snacks', calories: 40, serving: '2 tbsp', protein: 0.8, carbs: 7, fat: 1 },
  { name: 'Tamarind Chutney', category: 'snacks', calories: 60, serving: '2 tbsp', protein: 0.3, carbs: 15, fat: 0.1 },
  { name: 'Mango Pickle', category: 'snacks', calories: 35, serving: '1 tbsp', protein: 0.3, carbs: 2, fat: 2.8 },
  { name: 'Salsa', category: 'snacks', calories: 10, serving: '2 tbsp', protein: 0.4, carbs: 2, fat: 0.1 },
  { name: 'Soy Sauce', category: 'snacks', calories: 9, serving: '1 tbsp', protein: 1.3, carbs: 0.8, fat: 0 },
  { name: 'Honey', category: 'snacks', calories: 64, serving: '1 tbsp', protein: 0.1, carbs: 17, fat: 0 },
  { name: 'Jam (mixed fruit)', category: 'snacks', calories: 56, serving: '1 tbsp', protein: 0.1, carbs: 14, fat: 0 },
  { name: 'Nutella', category: 'snacks', calories: 100, serving: '1 tbsp', protein: 1, carbs: 11, fat: 6 },
  { name: 'Olive Oil', category: 'snacks', calories: 119, serving: '1 tbsp', protein: 0, carbs: 0, fat: 13.5 },
  { name: 'Coconut Oil', category: 'snacks', calories: 117, serving: '1 tbsp', protein: 0, carbs: 0, fat: 13.5 },
  { name: 'Mustard Oil', category: 'snacks', calories: 124, serving: '1 tbsp', protein: 0, carbs: 0, fat: 14 },

  // ── Drinks ──────────────────────────────────────────────────────────────
  { name: 'Tea with Milk & Sugar', category: 'drinks', calories: 60, serving: '1 cup', protein: 1.5, carbs: 9, fat: 2 },
  { name: 'Black Coffee', category: 'drinks', calories: 2, serving: '1 cup', protein: 0.3, carbs: 0, fat: 0 },
  { name: 'Cappuccino', category: 'drinks', calories: 80, serving: '1 cup', protein: 4, carbs: 7, fat: 4 },
  { name: 'Cold Coffee (sweetened)', category: 'drinks', calories: 180, serving: '1 glass', protein: 5, carbs: 28, fat: 5.5 },
  { name: 'Orange Juice', category: 'drinks', calories: 112, serving: '1 cup', protein: 1.7, carbs: 26, fat: 0.5 },
  { name: 'Coconut Water', category: 'drinks', calories: 46, serving: '1 cup', protein: 1.7, carbs: 9, fat: 0.5 },
  { name: 'Soft Drink (cola)', category: 'drinks', calories: 140, serving: '1 can (330 ml)', protein: 0, carbs: 39, fat: 0 },
  { name: 'Sports Drink', category: 'drinks', calories: 80, serving: '1 bottle (350 ml)', protein: 0, carbs: 21, fat: 0 },
  { name: 'Beer', category: 'drinks', calories: 154, serving: '1 bottle (355 ml)', protein: 1.6, carbs: 13, fat: 0 },
  { name: 'Wine (red)', category: 'drinks', calories: 125, serving: '1 glass (150 ml)', protein: 0.1, carbs: 3.8, fat: 0 },
  { name: 'Smoothie (banana + milk)', category: 'drinks', calories: 220, serving: '1 glass', protein: 8, carbs: 40, fat: 4 },
  { name: 'Sugarcane Juice', category: 'drinks', calories: 180, serving: '1 glass', protein: 0, carbs: 45, fat: 0 },
  { name: 'Green Tea', category: 'drinks', calories: 2, serving: '1 cup', protein: 0.2, carbs: 0.3, fat: 0 },
  { name: 'Black Tea (no sugar)', category: 'drinks', calories: 2, serving: '1 cup', protein: 0.1, carbs: 0.4, fat: 0 },
  { name: 'Masala Chai', category: 'drinks', calories: 100, serving: '1 cup', protein: 2.5, carbs: 14, fat: 3.5 },
  { name: 'Filter Coffee', category: 'drinks', calories: 90, serving: '1 cup', protein: 2.5, carbs: 11, fat: 4 },
  { name: 'Latte', category: 'drinks', calories: 150, serving: '1 tall', protein: 8, carbs: 14, fat: 7 },
  { name: 'Americano', category: 'drinks', calories: 5, serving: '1 cup', protein: 0.5, carbs: 1, fat: 0 },
  { name: 'Espresso', category: 'drinks', calories: 3, serving: '1 shot', protein: 0.2, carbs: 0.5, fat: 0.1 },
  { name: 'Mocha', category: 'drinks', calories: 290, serving: '1 tall', protein: 10, carbs: 35, fat: 12 },
  { name: 'Cold Brew Coffee', category: 'drinks', calories: 5, serving: '1 glass', protein: 0.3, carbs: 1, fat: 0 },
  { name: 'Iced Tea (sweetened)', category: 'drinks', calories: 90, serving: '1 glass', protein: 0, carbs: 23, fat: 0 },
  { name: 'Nimbu Pani (lemonade)', category: 'drinks', calories: 60, serving: '1 glass', protein: 0.1, carbs: 16, fat: 0 },
  { name: 'Jaljeera', category: 'drinks', calories: 30, serving: '1 glass', protein: 0.5, carbs: 7, fat: 0 },
  { name: 'Aam Panna', category: 'drinks', calories: 110, serving: '1 glass', protein: 0.5, carbs: 27, fat: 0.2 },
  { name: 'Thandai', category: 'drinks', calories: 240, serving: '1 glass', protein: 7, carbs: 30, fat: 10 },
  { name: 'Badam Milk', category: 'drinks', calories: 220, serving: '1 glass', protein: 8, carbs: 28, fat: 9 },
  { name: 'Hot Chocolate', category: 'drinks', calories: 250, serving: '1 cup', protein: 9, carbs: 32, fat: 10 },
  { name: 'Chocolate Milkshake', category: 'drinks', calories: 360, serving: '1 glass', protein: 10, carbs: 55, fat: 12 },
  { name: 'Mango Milkshake', category: 'drinks', calories: 300, serving: '1 glass', protein: 8, carbs: 50, fat: 8 },
  { name: 'Oreo Shake', category: 'drinks', calories: 450, serving: '1 glass', protein: 9, carbs: 62, fat: 19 },
  { name: 'Falooda', category: 'drinks', calories: 380, serving: '1 glass', protein: 8, carbs: 60, fat: 12 },
  { name: 'Apple Juice', category: 'drinks', calories: 114, serving: '1 cup', protein: 0.2, carbs: 28, fat: 0.3 },
  { name: 'Pomegranate Juice', category: 'drinks', calories: 134, serving: '1 cup', protein: 0.4, carbs: 33, fat: 0.7 },
  { name: 'Watermelon Juice', category: 'drinks', calories: 71, serving: '1 glass', protein: 1, carbs: 17, fat: 0.3 },
  { name: 'Mosambi Juice', category: 'drinks', calories: 120, serving: '1 glass', protein: 1, carbs: 28, fat: 0.5 },
  { name: 'Mixed Fruit Juice', category: 'drinks', calories: 130, serving: '1 glass', protein: 1, carbs: 31, fat: 0.3 },
  { name: 'ABC Juice (apple-beet-carrot)', category: 'drinks', calories: 100, serving: '1 glass', protein: 2, carbs: 23, fat: 0.3 },
  { name: 'Green Smoothie', category: 'drinks', calories: 130, serving: '1 glass', protein: 3, carbs: 28, fat: 1.5 },
  { name: 'Protein Smoothie (PB + banana)', category: 'drinks', calories: 350, serving: '1 glass', protein: 20, carbs: 40, fat: 13 },
  { name: 'Energy Drink', category: 'drinks', calories: 110, serving: '1 can (250 ml)', protein: 0, carbs: 28, fat: 0 },
  { name: 'Diet Cola', category: 'drinks', calories: 1, serving: '1 can (330 ml)', protein: 0, carbs: 0.2, fat: 0 },
  { name: 'Lemon Soft Drink', category: 'drinks', calories: 140, serving: '1 can (330 ml)', protein: 0, carbs: 37, fat: 0 },
  { name: 'Tonic Water', category: 'drinks', calories: 83, serving: '1 glass (240 ml)', protein: 0, carbs: 21, fat: 0 },
  { name: 'Kombucha', category: 'drinks', calories: 50, serving: '1 bottle (475 ml)', protein: 0, carbs: 12, fat: 0 },
  { name: 'Probiotic Drink (Yakult)', category: 'drinks', calories: 50, serving: '1 bottle (65 ml)', protein: 0.8, carbs: 11, fat: 0 },
  { name: 'Electrolyte Drink (ORS)', category: 'drinks', calories: 50, serving: '1 glass (200 ml)', protein: 0, carbs: 13, fat: 0 },
  { name: 'Sattu Drink', category: 'drinks', calories: 150, serving: '1 glass', protein: 7, carbs: 25, fat: 2 },
  { name: 'Rooh Afza Milk', category: 'drinks', calories: 180, serving: '1 glass', protein: 5, carbs: 30, fat: 4 },
  { name: 'Bournvita / Horlicks Milk', category: 'drinks', calories: 220, serving: '1 glass', protein: 9, carbs: 30, fat: 7 },
  { name: 'Bubble Tea (boba)', category: 'drinks', calories: 320, serving: '1 glass', protein: 2, carbs: 54, fat: 9 },

  // ── Fast food ───────────────────────────────────────────────────────────
  { name: 'Margherita Pizza', category: 'fastfood', calories: 250, serving: '1 slice', protein: 10, carbs: 31, fat: 9 },
  { name: 'Chicken Burger', category: 'fastfood', calories: 450, serving: '1 burger', protein: 22, carbs: 42, fat: 21 },
  { name: 'Veg Burger', category: 'fastfood', calories: 390, serving: '1 burger', protein: 10, carbs: 50, fat: 16 },
  { name: 'French Fries', category: 'fastfood', calories: 320, serving: '1 medium', protein: 4, carbs: 43, fat: 15 },
  { name: 'Chicken Nuggets', category: 'fastfood', calories: 270, serving: '6 pieces', protein: 14, carbs: 16, fat: 17 },
  { name: 'Momos (veg, steamed)', category: 'fastfood', calories: 210, serving: '6 pieces', protein: 7, carbs: 36, fat: 4 },
  { name: 'Momos (chicken, steamed)', category: 'fastfood', calories: 250, serving: '6 pieces', protein: 14, carbs: 32, fat: 7 },
  { name: 'Spring Roll', category: 'fastfood', calories: 160, serving: '1 roll', protein: 3, carbs: 20, fat: 7.5 },
  { name: 'Shawarma (chicken)', category: 'fastfood', calories: 430, serving: '1 wrap', protein: 26, carbs: 42, fat: 17 },
  { name: 'Hot Dog', category: 'fastfood', calories: 290, serving: '1 piece', protein: 10, carbs: 24, fat: 17 },
  { name: 'Tacos (chicken)', category: 'fastfood', calories: 210, serving: '1 taco', protein: 12, carbs: 18, fat: 10 },
  { name: 'Sushi Roll (california)', category: 'fastfood', calories: 255, serving: '8 pieces', protein: 9, carbs: 38, fat: 7 },
  { name: 'Pepperoni Pizza', category: 'fastfood', calories: 300, serving: '1 slice', protein: 12, carbs: 34, fat: 12.5 },
  { name: 'Farmhouse Pizza (veg)', category: 'fastfood', calories: 270, serving: '1 slice', protein: 10, carbs: 33, fat: 11 },
  { name: 'Cheese Burst Pizza', category: 'fastfood', calories: 360, serving: '1 slice', protein: 13, carbs: 36, fat: 18 },
  { name: 'Cheeseburger', category: 'fastfood', calories: 500, serving: '1 burger', protein: 25, carbs: 41, fat: 26 },
  { name: 'Double Cheeseburger', category: 'fastfood', calories: 650, serving: '1 burger', protein: 34, carbs: 43, fat: 37 },
  { name: 'Aloo Tikki Burger', category: 'fastfood', calories: 340, serving: '1 burger', protein: 7, carbs: 50, fat: 12 },
  { name: 'Paneer Wrap', category: 'fastfood', calories: 380, serving: '1 wrap', protein: 13, carbs: 45, fat: 16 },
  { name: 'Fried Chicken (1 piece)', category: 'fastfood', calories: 280, serving: '1 piece', protein: 19, carbs: 10, fat: 18.5 },
  { name: 'Chicken Wings', category: 'fastfood', calories: 430, serving: '6 wings', protein: 32, carbs: 8, fat: 29.5 },
  { name: 'Chicken Popcorn', category: 'fastfood', calories: 380, serving: '1 regular', protein: 17, carbs: 25, fat: 23.5 },
  { name: 'Fish and Chips', category: 'fastfood', calories: 780, serving: '1 plate', protein: 32, carbs: 75, fat: 39 },
  { name: 'Momos (fried)', category: 'fastfood', calories: 350, serving: '6 pieces', protein: 9, carbs: 40, fat: 17 },
  { name: 'Tandoori Momos', category: 'fastfood', calories: 320, serving: '6 pieces', protein: 11, carbs: 34, fat: 15.5 },
  { name: 'Frankie (veg)', category: 'fastfood', calories: 330, serving: '1 roll', protein: 7, carbs: 46, fat: 13 },
  { name: 'Egg Roll (street style)', category: 'fastfood', calories: 400, serving: '1 roll', protein: 13, carbs: 42, fat: 19.5 },
  { name: 'Falafel (4 pieces)', category: 'fastfood', calories: 170, serving: '4 pieces', protein: 6, carbs: 16, fat: 9.5 },
  { name: 'Onion Rings', category: 'fastfood', calories: 280, serving: '1 regular', protein: 3.5, carbs: 33, fat: 15 },
  { name: 'Hash Browns', category: 'fastfood', calories: 150, serving: '1 piece', protein: 1.5, carbs: 16, fat: 8.5 },
  { name: 'Nachos with Cheese', category: 'fastfood', calories: 350, serving: '1 plate', protein: 8, carbs: 38, fat: 18.5 },
  { name: 'Chilli Potato', category: 'fastfood', calories: 350, serving: '1 plate', protein: 4, carbs: 45, fat: 17.5 },
  { name: 'Burrito (bean)', category: 'fastfood', calories: 450, serving: '1 burrito', protein: 15, carbs: 62, fat: 16 },
  { name: 'Sub Sandwich (6-inch, veg)', category: 'fastfood', calories: 280, serving: '1 sub', protein: 10, carbs: 46, fat: 6 },
  { name: 'Sub Sandwich (6-inch, chicken)', category: 'fastfood', calories: 320, serving: '1 sub', protein: 23, carbs: 46, fat: 6 },
  { name: 'Instant Noodles (masala)', category: 'fastfood', calories: 380, serving: '1 pack', protein: 8, carbs: 54, fat: 14 },
  { name: 'Corn Dog', category: 'fastfood', calories: 250, serving: '1 piece', protein: 7, carbs: 28, fat: 12 },
  { name: 'Salmon Nigiri (2 pieces)', category: 'fastfood', calories: 70, serving: '2 pieces', protein: 4, carbs: 14, fat: 0.5 },
];

// ── Serving parsing ──────────────────────────────────────────────────────────
// Lets the quantity sheet work in natural units: "6 pieces" steps per piece,
// "100 g" takes a grams input, "1 bowl" falls back to a servings multiplier.

export type ServingMode = 'pieces' | 'weight' | 'servings';

export interface ParsedServing {
  mode: ServingMode;
  /** pieces: units in ONE base serving ("6 pieces" → 6). */
  count: number;
  /** Unit word(s) without parentheticals — "pieces", "nuts", "medium". */
  unit: string;
  /** weight: grams/ml in one base serving ("100 g" → 100). */
  baseWeight: number | null;
  /** 'g' or 'ml' for weight mode. */
  weightUnit: 'g' | 'ml' | null;
}

export function parseServing(serving: string): ParsedServing {
  const s = serving.trim();
  const lead = s.match(/^(\d+(?:\.\d+)?)\s*(.*)$/);
  const count = lead ? parseFloat(lead[1]) : NaN;
  const rest = (lead ? lead[2] : s).replace(/\(.*?\)/g, '').trim();

  // "100 g", "330 ml", "150 g cooked" — the serving IS a weight/volume.
  const weightMatch = rest.match(/^(g|ml)\b/i);
  if (lead && weightMatch && Number.isFinite(count) && count > 0) {
    const wu = weightMatch[1].toLowerCase() as 'g' | 'ml';
    return { mode: 'weight', count: 1, unit: wu, baseWeight: count, weightUnit: wu };
  }

  // "6 pieces", "23 nuts (28 g)", "4 squares" — countable units.
  if (lead && Number.isFinite(count) && count > 1 && rest) {
    return { mode: 'pieces', count: Math.round(count), unit: rest, baseWeight: null, weightUnit: null };
  }

  // "1 medium", "1 katori", "⅔ cup", "1 bar (44 g)" — one nameable serving.
  return { mode: 'servings', count: 1, unit: rest || 'serving', baseWeight: null, weightUnit: null };
}

/** "4 pieces" / "1 piece" — naive singular for the n === 1 case. */
export function unitLabel(n: number, unit: string): string {
  if (n !== 1) return unit;
  if (unit === 'halves') return 'half';
  return unit.replace(/s$/, '');
}

/**
 * Case-insensitive library search; prefix matches rank above substring
 * matches so "pa" surfaces Paratha/Paneer before Chapati. `extra` lets
 * callers blend in user-saved foods, which list ahead of built-ins.
 */
export function searchFoods(
  query: string,
  category?: FoodCategory | 'all',
  extra: FoodItem[] = [],
): FoodItem[] {
  // A user food named like a built-in replaces it — duplicate names would
  // otherwise show two rows sharing one (name-keyed) favourite state.
  const extraNames = new Set(extra.map((f) => f.name.toLowerCase()));
  const all = [...extra, ...FOOD_LIBRARY.filter((f) => !extraNames.has(f.name.toLowerCase()))];
  const pool = !category || category === 'all'
    ? all
    : all.filter((f) => f.category === category);
  const q = query.trim().toLowerCase();
  if (!q) return pool;
  const starts: FoodItem[] = [];
  const contains: FoodItem[] = [];
  for (const f of pool) {
    const name = f.name.toLowerCase();
    if (name.startsWith(q)) starts.push(f);
    else if (name.includes(q)) contains.push(f);
  }
  return [...starts, ...contains];
}
