import { StyleSheet } from 'react-native';
import { theme, withAlpha } from '../theme';

const recordsAccent = theme.colors.families.records.accent;
const socialAccent = theme.colors.families.social.accent;

export const goalMarkdownStyles = StyleSheet.create({
  body: { color: theme.colors.text, fontSize: 13, lineHeight: 20 },
  heading1: { color: theme.colors.text, fontSize: 16, fontWeight: '700', marginBottom: 4, marginTop: 6 },
  heading2: { color: theme.colors.text, fontSize: 14, fontWeight: '700', marginBottom: 3, marginTop: 4 },
  heading3: { color: theme.colors.primary, fontSize: 13, fontWeight: '700', marginBottom: 2, marginTop: 3 },
  strong: { fontWeight: '700', color: theme.colors.text },
  em: { fontStyle: 'italic', color: theme.colors.textSecondary },
  bullet_list: { marginVertical: 4 },
  ordered_list: { marginVertical: 4 },
  code_inline: { backgroundColor: withAlpha(theme.colors.text, 'soft'), borderRadius: 4, paddingHorizontal: 4, color: socialAccent, fontSize: 12 },
  fence: { backgroundColor: theme.colors.surfaceMuted, borderRadius: 8, padding: 10, marginVertical: 4, borderWidth: 1, borderColor: theme.colors.border },
  table: { borderWidth: 1, borderColor: theme.colors.border, borderRadius: 6, marginVertical: 6, overflow: 'hidden' },
  thead: { backgroundColor: withAlpha(theme.colors.primary, 'faint') },
  th: { padding: 6, fontWeight: '700', color: theme.colors.primary, fontSize: 11, borderRightWidth: 1, borderRightColor: theme.colors.border },
  td: { padding: 6, color: theme.colors.text, fontSize: 11, borderRightWidth: 1, borderRightColor: theme.colors.border },
  tr: { borderBottomWidth: 1, borderBottomColor: theme.colors.border, flexDirection: 'row' },
  paragraph: { marginVertical: 2 },
  link: { color: theme.colors.info },
  blockquote: { backgroundColor: withAlpha(theme.colors.primary, 'faint'), borderLeftWidth: 3, borderLeftColor: theme.colors.primary, paddingLeft: 8, marginVertical: 4, borderRadius: 4 },
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContent: {
    paddingBottom: 130,
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 20,
    marginBottom: 16,
  },
  heroTitle: { fontSize: 24, fontFamily: theme.fonts.display, color: theme.colors.onAccent },
  heroSub: { fontSize: 12, color: withAlpha(theme.colors.onAccent, 'heavy'), marginTop: 4 },
  heroAddBtn: {
    width: 48, height: 48, borderRadius: 24,
    backgroundColor: withAlpha(theme.colors.onAccent, 'tint'),
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, borderColor: withAlpha(theme.colors.onAccent, 'medium'),
    ...theme.shadows.md,
  },

  emptyState: {
    alignItems: 'center', justifyContent: 'center',
    paddingHorizontal: 24, paddingVertical: 48,
    marginHorizontal: 16,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.xl,
    borderWidth: 1, borderColor: theme.colors.border,
    marginBottom: 16,
  },
  emptyIconRing: {
    width: 82, height: 82, borderRadius: 41,
    alignItems: 'center', justifyContent: 'center',
    marginBottom: 16,
    ...theme.shadows.glow(theme.colors.primary),
  },
  emptyIconWrap: {
    width: 76, height: 76, borderRadius: 38,
    alignItems: 'center', justifyContent: 'center',
    backgroundColor: theme.colors.surfaceElevated,
  },
  emptyTitle: { ...theme.typography.heading, color: theme.colors.text },
  emptySub: { ...theme.typography.footnote, color: theme.colors.textSecondary, marginTop: 6, textAlign: 'center', maxWidth: 280 },
  emptyFeatures: {
    alignSelf: 'stretch',
    marginTop: 20,
    gap: 4,
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: theme.borderRadius.lg,
    borderWidth: 1, borderColor: theme.colors.border,
    paddingVertical: 6, paddingHorizontal: 12,
  },
  emptyFeatureRow: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    paddingVertical: 9,
  },
  emptyFeatureIcon: {
    width: 30, height: 30, borderRadius: 10,
    alignItems: 'center', justifyContent: 'center',
    backgroundColor: withAlpha(theme.colors.primary, 'soft'),
  },
  emptyFeatureText: { ...theme.typography.footnote, color: theme.colors.textSecondary, flex: 1 },
  emptyFootnote: { ...theme.typography.micro, color: theme.colors.textSecondary, marginTop: 12 },

  goalCard: {
    padding: theme.spacing.lg,
    marginBottom: theme.spacing.lg,
    marginHorizontal: theme.spacing.md,
  },

  // ── Card header ──
  goalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: theme.spacing.md,
  },
  goalTitleRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 8,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  iconButton: {
    padding: 6,
    backgroundColor: withAlpha(theme.colors.text, 'faint'),
    borderRadius: theme.borderRadius.sm,
  },
  daysChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    alignSelf: 'flex-start',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: theme.borderRadius.full,
    backgroundColor: theme.colors.families.plan.tint,
    borderWidth: 1,
    borderColor: withAlpha(theme.colors.families.plan.accent, 'strong'),
    marginTop: 6,
  },
  daysChipText: { ...theme.typography.label, color: theme.colors.families.plan.accent },

  // ── TODAY block ──
  todayCard: {
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.surfaceMuted,
    borderWidth: 1,
  },
  todayHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  todayEyebrow: { ...theme.typography.label, color: theme.colors.textSecondary, textTransform: 'uppercase' },
  kindChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: theme.borderRadius.full,
    borderWidth: 1,
  },
  kindChipText: { ...theme.typography.label, textTransform: 'uppercase' },
  todayTitle: { ...theme.typography.subtitle, color: theme.colors.text },
  todayDesc: { ...theme.typography.footnote, color: theme.colors.textSecondary, marginTop: 3 },
  todayPillsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  todayPill: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    paddingHorizontal: 8, paddingVertical: 3, borderRadius: theme.borderRadius.sm,
    borderWidth: 1,
  },
  todayPillText: { ...theme.typography.caption },
  restNote: {
    marginTop: 8,
    padding: 10,
    borderRadius: theme.borderRadius.sm,
    backgroundColor: withAlpha(theme.colors.info, 'soft'),
    borderLeftWidth: 2,
    borderLeftColor: theme.colors.info,
  },
  todayActions: { flexDirection: 'row', gap: 10, marginTop: 12 },
  todayStateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    padding: 10,
    borderRadius: theme.borderRadius.sm,
    backgroundColor: withAlpha(theme.colors.text, 'faint'),
  },
  todayStateText: { ...theme.typography.footnote, flex: 1 },

  // ── Phase stepper ──
  stepperRow: { flexDirection: 'row', gap: 8, paddingVertical: 2 },
  stepperPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    height: 30,
    borderRadius: theme.borderRadius.full,
    borderWidth: 1.5,
    overflow: 'hidden',
  },
  stepperPillDone: { borderColor: withAlpha(theme.colors.success, 'strong') },
  stepperPillActive: { borderColor: 'transparent' },
  stepperPillFuture: { borderColor: theme.colors.border },
  stepperPillText: { ...theme.typography.caption },

  // ── Progress row ──
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.md,
    marginTop: theme.spacing.md,
  },
  progressBars: { flex: 1, gap: 10 },
  progressCaption: { ...theme.typography.footnote, color: theme.colors.textSecondary },
  barLabelRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  barLabel: { ...theme.typography.caption, color: theme.colors.textSecondary },
  barValue: { ...theme.typography.caption, color: theme.colors.text },
  progressDialPct: { ...theme.typography.numericSm, color: theme.colors.text },
  progressDialCaption: { ...theme.typography.micro, color: theme.colors.textSecondary, letterSpacing: 1.2, marginTop: 2 },

  // ── Legacy AI goals without phases ──
  phaseBox: {
    backgroundColor: theme.colors.families.plan.tint,
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    borderLeftWidth: 3,
    borderLeftColor: theme.colors.families.plan.accent,
    marginTop: theme.spacing.md,
  },
  workoutBox: {
    marginTop: theme.spacing.md,
    padding: theme.spacing.md,
    backgroundColor: withAlpha(theme.colors.text, 'faint'),
    borderRadius: theme.borderRadius.md,
    borderLeftWidth: 2,
    borderLeftColor: recordsAccent,
  },

  // ── Simple-goal gradient card ──
  simpleCard: {
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing.md,
    marginTop: theme.spacing.xs,
  },
  simpleHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.md,
  },
  simpleHeaderLabel: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  simpleHeaderText: {
    color: withAlpha(theme.colors.onAccent, 'heavy'),
    ...theme.typography.label,
    textTransform: 'uppercase',
  },
  simpleNumberRow: { flexDirection: 'row', alignItems: 'flex-end', marginBottom: theme.spacing.xs },
  simpleNumber: {
    fontSize: 44,
    fontFamily: theme.fonts.display,
    color: theme.colors.onAccent,
    lineHeight: 48,
    letterSpacing: -1,
    fontVariant: ['tabular-nums'],
    padding: 0,
  },
  simpleNumberUnit: { color: withAlpha(theme.colors.onAccent, 'heavy'), fontSize: 16, marginBottom: 6, marginLeft: 6 },
  simpleCaptionRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginBottom: theme.spacing.md },
  simpleCaption: { color: withAlpha(theme.colors.onAccent, 'heavy'), fontSize: 12 },
  simpleCaptionDone: { color: theme.colors.onAccent },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
  },

  // ── Chat ──
  chatBubbleUser: {
    alignSelf: 'flex-end',
    backgroundColor: withAlpha(theme.colors.primary, 'medium'),
    borderRadius: 12,
    borderBottomRightRadius: 2,
    paddingHorizontal: 12,
    paddingVertical: 8,
    maxWidth: '85%',
  },
  chatBubbleBot: {
    alignSelf: 'flex-start',
    backgroundColor: theme.colors.background,
    borderRadius: 12,
    borderBottomLeftRadius: 2,
    paddingHorizontal: 12,
    paddingVertical: 8,
    maxWidth: '90%',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  chatBubbleText: { fontSize: 13, color: theme.colors.text, lineHeight: 19 },

  // ── Plan diff sheet ──
  diffPhaseBox: {
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    backgroundColor: withAlpha(theme.colors.text, 'faint'),
    borderWidth: 1,
    borderColor: theme.colors.divider,
    marginBottom: 10,
  },
  diffPhaseName: { ...theme.typography.subtitle, color: theme.colors.text },
  diffMetaRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 },
  diffMetaLabel: { ...theme.typography.caption, color: theme.colors.textSecondary },
  diffOld: { ...theme.typography.footnote, color: theme.colors.textSecondary, textDecorationLine: 'line-through' },
  diffNew: { ...theme.typography.footnote, color: theme.colors.families.plan.accent },
  diffUnchanged: { ...theme.typography.footnote, color: theme.colors.text },
  diffHighlight: {
    marginTop: 12,
    padding: 10,
    borderRadius: theme.borderRadius.sm,
    backgroundColor: theme.colors.families.plan.tint,
    borderLeftWidth: 2,
    borderLeftColor: theme.colors.families.plan.accent,
  },

  // ── Phase detail sheet ──
  phaseMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
  },
  phaseMetaLabel: { ...theme.typography.footnote, color: theme.colors.textSecondary },
  phaseMetaValue: { ...theme.typography.footnote, color: theme.colors.text },
});
