import { StyleSheet } from 'react-native';
import { theme, withAlpha } from '../../theme';

export const styles = StyleSheet.create({
  prescBox: {
    backgroundColor: withAlpha(theme.colors.text, 'faint'),
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    borderLeftWidth: 3,
  },
  prescKindRow: { flexDirection: 'row', marginBottom: 8 },
  kindChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: theme.borderRadius.full,
    borderWidth: 1,
  },
  kindChipText: { ...theme.typography.label, textTransform: 'uppercase' },
  prescDesc: { lineHeight: 18, marginBottom: 10 },
  prescMetaRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  prescMetaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    backgroundColor: withAlpha(theme.colors.text, 'soft'),
  },
  prescMetaText: { ...theme.typography.caption, color: theme.colors.text },
  restBox: {
    marginTop: 12,
    padding: 10,
    borderRadius: theme.borderRadius.sm,
    backgroundColor: withAlpha(theme.colors.info, 'soft'),
    borderLeftWidth: 2,
    borderLeftColor: theme.colors.info,
  },
  verdictRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: theme.borderRadius.sm,
  },
  verdictChip: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: theme.borderRadius.full,
  },
  verdictChipText: { ...theme.typography.label, textTransform: 'uppercase' },
  verdictText: { flex: 1, color: theme.colors.text },
  futureHint: {
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginTop: 18,
    marginBottom: 6,
  },
  sectionLabel: { marginTop: 18, marginBottom: 8 },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1.5,
    borderColor: theme.colors.border,
    backgroundColor: withAlpha(theme.colors.text, 'faint'),
    marginBottom: 8,
  },
  activityRowSelected: {
    borderColor: theme.colors.success,
    backgroundColor: withAlpha(theme.colors.success, 'soft'),
  },
  activityName: { ...theme.typography.body, color: theme.colors.text },
  activityMeta: { ...theme.typography.footnote, color: theme.colors.textSecondary, marginTop: 2 },
  choiceRow: { flexDirection: 'row', gap: 10 },
  rpeRow: { flexDirection: 'row', gap: 4, flexWrap: 'wrap' },
  rpePill: {
    minWidth: 28,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: theme.borderRadius.sm,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
  },
  rpeText: { ...theme.typography.caption, color: theme.colors.textSecondary },
  rpeHint: { marginTop: 6, color: theme.colors.textSecondary },
  notesInput: {
    backgroundColor: theme.colors.background,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.sm,
    padding: theme.spacing.md,
    color: theme.colors.text,
    fontSize: 15,
    minHeight: 70,
    textAlignVertical: 'top',
  },
});
