import { StyleSheet } from 'react-native';
import { theme, withAlpha } from '../../theme';

export const styles = StyleSheet.create({
  wrap: {
    marginTop: theme.spacing.md,
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    backgroundColor: withAlpha(theme.colors.text, 'faint'),
    borderWidth: 1,
    borderColor: theme.colors.divider,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  headerCopy: { flex: 1, alignItems: 'center' },
  weekLabel: { color: theme.colors.text },
  weekRange: {
    ...theme.typography.micro,
    color: theme.colors.textSecondary,
    marginTop: 2,
  },
  arrowBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  arrowBtnDisabled: { opacity: theme.opacity.disabled },
  syncBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: theme.colors.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  syncBtnLabel: { ...theme.typography.caption, color: theme.colors.text },
  row: { flexDirection: 'row', gap: 6 },
  chipCell: { flex: 1 },
  chip: {
    minHeight: 72,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    paddingHorizontal: 2,
    borderRadius: 10,
    backgroundColor: withAlpha(theme.colors.text, 'faint'),
    borderWidth: 1.5,
  },
  chipMissed: { opacity: 0.55 },
  chipLabel: { ...theme.typography.caption, color: theme.colors.textSecondary },
  chipDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 4,
  },
  chipKind: { ...theme.typography.micro, fontSize: 9, color: theme.colors.textSecondary },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
  },
  summaryText: { ...theme.typography.footnote, color: theme.colors.textSecondary },
});
